Support multicore configs in bp_axi_top
black-parrot/black-parrot pull request #1079
Opened 2022-03-31 05:46 UTC by muwyse

## Summary
This PR enables multicore configs in bp_axi_top, which is particularly useful for Zynq FPGA platforms. There is a minor reorg in the module, but unicore design should be unchanged. Multicore design logic is changed to use new BedRock Burst to AXIL converters.

## Area
bp_axi_top, with minor change to axil converters and addition of new burst-axil converters

## Additional Changes Required (if any)
Test changes in zynq-parrot before merge and bumping BP RTL

## Analysis
No changes for unicore, enables multicore designs

## Verification
We do not currently run bp_axi_top in the BP RTL CI, so changes need to be verified in zynq-parrot repo.

## Required Before Merge

- [ ] verify unicore functionality unchanged in zynq-parrot
- [ ] verify multicore configs simulate properly in zynq-parrot cosim flow for > 2 cores
- [ ] verify bp_multicore_1_cfg functional in zynq-parrot on FPGA

2022-03-31 06:21 UTC, dpetrisko commented on bp_me/src/v/network/bp_me_axil_client.sv
> +        // NOTE: wsize and s_axil_awaddr_r only become valid when r&v axi signals high
I'm not sure I understand the concern. When axi valid is high, the lines are valid and guaranteed to remain high by the spec. When the r&v occurs, that's when the transaction actually happens

2022-03-31 06:22 UTC, dpetrisko commented on bp_me/src/v/network/bp_me_axil_to_burst.sv
> +            || io_resp_header_cast_i.size < e_bedrock_msg_size_64
msg_size_8?

2022-03-31 06:23 UTC, dpetrisko commented on bp_me/src/v/network/bp_me_axil_to_burst.sv
> +            || io_resp_header_cast_i.size < e_bedrock_msg_size_64
this should also just check for single beat transaction

2022-03-31 06:23 UTC, dpetrisko commented on bp_me/src/v/network/bp_me_burst_to_axil.sv
> +    assert (reset_i !== '0 || ~io_cmd_header_v_i
same comments as other

2022-03-31 06:30 UTC, dpetrisko commented on bp_top/src/v/bp_axi_top.sv
> +  logic [num_cce_p-1:0][l2_banks_p-1:0] dma_pkt_v_o, dma_pkt_ready_and_i;
keep this as _li / _lo, per convention

2022-03-31 06:31 UTC, dpetrisko commented on bp_top/src/v/bp_axi_top.sv
> +      bp_me_bedrock_mem_to_link
May have been an easier route to just tunnel wormhole to axi-lite. But it's already written so c'est la vie

2022-03-31 06:32 UTC, dpetrisko commented on bp_top/src/v/bp_axi_top.sv
> +  logic [num_cce_p-1:0][l2_banks_p-1:0] dma_pkt_v_o, dma_pkt_ready_and_i;
suggest axi_dma to avoid name conflict

2022-03-31 06:33 UTC, dpetrisko commented on bp_top/src/v/bp_axi_top.sv
>     , input [1:0]                               m_axi_rresp_i
This makes me think of our friend's comment that having a wrapper for unicore/multicore would be useful, to avoid rewriting this logic in multiple systems. This would basically be the wrapper currently used in the cache testbench. What do you think about that?

2022-03-31 06:35 UTC, dpetrisko commented on bp_me/src/v/network/bp_me_burst_to_axil.sv
> +module bp_me_burst_to_axil
nice, these modules seem to follow the handshakes appropriately. Of course, the single beat write restriction makes things simpler

2022-03-31 15:26 UTC, muwyse commented on bp_me/src/v/network/bp_me_axil_client.sv
> +        // NOTE: wsize and s_axil_awaddr_r only become valid when r&v axi signals high
Yes, the input lines remain high, but the output io_cmd doesn't actually become valid until the s_axil_awaddr_r signal is valid. Due to how the register enable is wired above, this actually doesn't happen until the io_cmd handshake. So, the io command is being output valid before the contents of the header are actually valid. This causes problems if the consumer examines the header before raising ready_and_i in a following cycle (allowed by BedRock).

2022-03-31 15:27 UTC, muwyse commented on bp_me/src/v/network/bp_me_axil_to_burst.sv
> +            || io_resp_header_cast_i.size < e_bedrock_msg_size_64
ah, yes. Mind was probably thinking bits not bytes.

2022-03-31 15:29 UTC, muwyse commented on bp_me/src/v/network/bp_me_burst_to_axil.sv
> +module bp_me_burst_to_axil
Yep. They are not meant to be high performance or fully support all possible transactions (BedRock or AXI). Functionally, they should be the same as bp_me_axil_client|master

2022-03-31 15:32 UTC, muwyse commented on bp_top/src/v/bp_axi_top.sv
>     , input [1:0]                               m_axi_rresp_i
Not sure I follow. The cache testbench wrapper has cache packet on one side and BedRock on the other, both of which are BP specific interfaces. I think this is a very nice top-level wrapper for BP since it is AXIL and AXI only, so should be easy to connect to other systems.

2022-03-31 15:37 UTC, dpetrisko commented on bp_top/src/v/bp_axi_top.sv
>     , input [1:0]                               m_axi_rresp_i
Sorry, suggestion is to encompass the internals of this block in bp_top.sv. So we have:
testbench->wrapper->bp_top
axi_top->bp_top
bsg_fpga->bp_top

We just have this if (unicore) bp_unicore else bp_multicore code in several places

2022-03-31 15:47 UTC, muwyse commented on bp_top/src/v/bp_axi_top.sv
> +      bp_me_bedrock_mem_to_link
Perhaps. It still requires extracting the BedRock message information from the WH network to properly transduce to/from AXI. I think the overhead we should look for here is any gearboxing on the data channels. Ideally, WH flit width == bedrock data width == axi data width.

2022-04-01 03:04 UTC, dpetrisko commented on bp_top/src/v/bp_axi_top.sv
>     , input [1:0]                               m_axi_rresp_i
I won't block this on this comment, but probably next time week change this code it's a good idea

2022-04-01 03:05 UTC, dpetrisko commented on bp_common/src/include/bp_common_aviary_pkgdef.svh
> -      ,l2_banks: 1
This breaks certain parts of the infrastructure with the current implementation of bsg_round_robin:   if (dram_type_p == "axi" && (num_cce_p*l2_banks_p) > 16)

2022-04-01 03:06 UTC, dpetrisko approved these changes
I would revert the bank change to avoid surprises, but other than that GTG

2022-04-01 03:08 UTC, dpetrisko commented
Let's merge into dev directly though, I'm trying to put together a release and we don't need another CI run

2022-04-01 03:15 UTC, dpetrisko commented on bp_me/src/v/network/bp_me_axil_client.sv
> +        // NOTE: wsize and s_axil_awaddr_r only become valid when r&v axi signals high
No, I still don't understand. They shouldn't, or it wouldn't be a ready_and_i handshake

2022-04-01 03:19 UTC, dpetrisko commented on bp_common/src/include/bp_common_aviary_pkgdef.svh
> -      ,l2_banks: 1
Oh I see the default is 1 for multicore. What is that?

2022-04-01 03:21 UTC, dpetrisko requested changes
Handshake fix requested

2022-04-01 03:21 UTC, dpetrisko commented on bp_me/src/v/network/bp_me_axil_client.sv
> +        // NOTE: wsize and s_axil_awaddr_r only become valid when r&v axi signals high
Oh, I see. That's incorrect then. The flop enables should be

is_ready & s_axil_wvalid_i
is_ready & s_axil_awvalid_i

2022-04-01 04:24 UTC, muwyse commented on bp_common/src/include/bp_common_aviary_pkgdef.svh
> -      ,l2_banks: 1
I don't know why the default for multicore is 1 L2 bank. I don't recall changing that param, but good to know about the round robin supporting up to 16 only.

2022-04-01 06:25 UTC, muwyse commented on bp_common/src/include/bp_common_aviary_pkgdef.svh
> -      ,l2_banks: 1
Changed to use default of 2 L2 banks up to 8 cores, then 1 L2 bank for 12 and 16 cores. The multicore CI regression script passed locally for me.

2022-04-05 14:47 UTC, dpetrisko commented
With the issue raised for the handshake fix, is this good to go?

2022-04-05 15:10 UTC, muwyse commented
> With the issue raised for the handshake fix, is this good to go?

I have not yet confirmed this is working on ZP as expected. I have been splitting out SW/HW changes in ZP to test, and have only confirmed the SDK bump for ZP seems to work as expected.

2022-05-06 21:39 UTC, closed without merging