Fixes for I$ parameterization to 1KB
black-parrot/black-parrot pull request #1101
Opened 2022-07-18 20:39 UTC by KinzaQamar

Thanks for contributing to BlackParrot! Check out the CONTRIBUTING guide, if this is your first
time. A few details to check:

## Summary
Brief description of the change.

## Issue Fixed
Does this PR address a BlackParrot GitHub issue? Link it here:

## Area
Module/tool/makefile/script in question.

## Reasoning (outdated, confusing, verbose, etc.)
Why is this change required?

## Additional Changes Required (if any)
Next steps, downstream modules affected, etc.

## Analysis
Potential impact of the change.

## Verification
Steps to taken to verify the change.

## Additional Context
Add any other context about the problem here.
Logs, screenshots or videos that show the issue are very helpful.

2022-08-09 23:43 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  wire [vtag_width_p-1:0]     vaddr_vtag_tl = vaddr_tl_r[(vaddr_width_p-1)-:vtag_width_p];
Can you double check that the memory bypass logic is using the correct bits? I cannot see it in this changeset, but I believe it may be using the block and set bits rather than the full page offset

2022-08-09 23:43 UTC, dpetrisko commented on bp_common/src/include/bp_common_aviary_defines.svh
> +    , localparam ctag_width_p  = caddr_width_p - page_offset_width_gp															 \
Noting that we'll need a ctag per cache type

2022-08-09 23:47 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire unused_bits = ((block_offset_width_lp+sindex_width_lp) < page_offset_width_gp) ? 1'b1 : 1'b0;
Let me suggest a little cleaner implementation with a neat Verilog trick "zero-width concatenation".

localparam ctag_vbits_lp = page_offset_width_gp - block_offset_width_lp - sindex_width_lp;
wire [ctag_offset_bits_lp-1:0] ctag_vbits = page_offset_tl_r[page_offset_width_gp-1:block_offset_width_lp+sindex_width_lp];
wire [ctag_width_p-1:0] ctag_li = {ptag_i, {ctag_vbits_lp>0{ctag_vbits}}};

This will only do the concatenation if ctag_vbits_lp is greater than 0, otherwise it will use ptag_i directly. Additionally, it's nice to have the ctag_vbits_lp as its own variable as a sanity check in the waveform dump

2022-08-09 23:47 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  wire unused_bits = ((block_offset_width_lp+sindex_width_lp) < page_offset_width_gp) ? 1'b1 : 1'b0;
Same comment as D$

2022-08-09 23:48 UTC, dpetrisko requested changes
Great start, left some comments. I know there are additional changes incoming for heterogeneous configurations and multicore support

2022-08-10 18:10 UTC, KinzaQamar commented on bp_fe/src/v/bp_fe_icache.sv
> +  wire [vtag_width_p-1:0]     vaddr_vtag_tl = vaddr_tl_r[(vaddr_width_p-1)-:vtag_width_p];
Which signal is using full page offset? Can you point toward it?  Here is the memory bypass logic: https://github.com/KinzaQamar/black-parrot/blob/a10efba489a09883798531313089e32db2b740f2/bp_fe/src/v/bp_fe_icache.sv#L589
Which I believe is using the correct bits

2022-08-15 15:23 UTC, dpetrisko commented on bp_common/src/include/bp_common_aviary_defines.svh
> +    , localparam ctag_width_p  = caddr_width_p - page_offset_width_gp															 \
we can get rid of this generic ctag since we shouldn't be using it anywhere

2022-08-19 12:45 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam icache_ctag_width_lp   = caddr_width_p - (block_offset_width_lp + sindex_width_lp);
call this 'ctag_width_lp' to fully genericize it

2022-08-19 12:46 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  localparam dcache_ctag_width_lp     = caddr_width_p - (block_offset_width_lp + sindex_width_lp);
call this 'ctag_width_lp' to fully genericize it

2022-08-19 12:48 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam icache_ctag_width_lp   = caddr_width_p - (block_offset_width_lp + sindex_width_lp);
line 108 needs to change to use ctag_width_lp

2022-08-19 12:48 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  localparam dcache_ctag_width_lp     = caddr_width_p - (block_offset_width_lp + sindex_width_lp);
L199 needs to change to use ctag_width_lp

2022-08-19 12:49 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, lce_ctag_width_lp, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
calculate parameter ctag_width_lp (name change) above, cannot declare localparam after usage in most tools

2022-08-19 12:49 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce_cmd.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, lce_ctag_width_lp, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
calculate parameter ctag_width_lp (name change) above, cannot declare localparam after usage in most tools

2022-08-19 12:50 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce_fill.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, lce_ctag_width_lp, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
calculate parameter ctag_width_lp (name change) above, cannot declare localparam after usage in most tools

2022-08-19 12:50 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce_req.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, lce_ctag_width_lp, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
calculate parameter ctag_width_lp (name change) above, cannot declare localparam after usage in most tools

2022-08-19 12:50 UTC, dpetrisko commented on bp_top/test/common/bp_nonsynth_cache_tracer.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, ctag_width_lp, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
calculate parameter ctag_width_lp above, cannot declare localparam after usage in most tools

2022-08-19 16:20 UTC, KinzaQamar commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam icache_ctag_width_lp   = caddr_width_p - (block_offset_width_lp + sindex_width_lp);
> line 108 needs to change to use ctag_width_lp

I see. Yeah, I didn't copy the change everywhere. My bad!

2022-08-30 06:43 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  localparam ctag_width_lp     = caddr_width_p - (block_offset_width_lp + sindex_width_lp);
This needs to be moved to before L116, can't declare parameters after usage

2022-08-30 06:47 UTC, dpetrisko commented on bp_top/test/common/bp_nonsynth_cache_tracer.sv
> +   , localparam ctag_width_lp = caddr_width_p - (block_offset_width_lp+index_width_lp)
must be declared before L15, cannot declare parameter after usage

2022-08-30 06:47 UTC, dpetrisko commented on bp_top/test/common/bp_nonsynth_if_verif.sv
> +  if ((cce_type_p == e_cce_uce) && (page_offset_width_gp > 12))
don't need this assertion, page offset will never change

2022-08-30 06:49 UTC, dpetrisko commented on bp_top/test/common/bp_nonsynth_if_verif.sv
> +  if ((cce_type_p != e_cce_uce) && (page_offset_width_gp != 12))
We're not trying to check the page offset constant itself here; instead, we're testing if block_size*index_size > 4kB

2022-08-30 06:49 UTC, dpetrisko commented on bp_fe/test/common/bp_fe_nonsynth_icache_tracer.sv
> +   , localparam ctag_width_lp = caddr_width_p - (`BSG_SAFE_CLOG2(block_width_p*sets_p/8))
Need to declare before L15, cannot declare parameter after usage

2022-08-30 06:50 UTC, dpetrisko requested changes
Still need to adjust the localparam declarations; otherwise looks good

2022-09-27 11:28 UTC, dpetrisko commented
Hi @KinzaQamar, code looks good. can you do a rebase before merging?

2022-09-27 11:28 UTC, dpetrisko approved these changes

2022-10-10 03:30 UTC, dpetrisko approved these changes
LGTM!

2022-10-10 03:31 UTC, merged