BP Stream Design Between UCE and L2 adapter in unicore
black-parrot/black-parrot pull request #612
Opened 2020-08-23 04:18 UTC by Songchun-Li

This pull request include multiple changes to implement BP Stream Protocol between UCE and L2, which are
1. Separated out the header and data port for UCE.
2. Added lock signals for mem_cmd/resp.
3. Updated the logic with the new locking arbiter and the new cache adapter.
4. Add bp_me_cache_slice_new for the new cache adapter.

Note. The current design sends multiple cmds for cache read when the fill width is less than a cache block.

2020-10-15 09:23 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce_stream.v
> +// This uce_stream module sends only one request for cache block load
name bp_uce.  Otherwise, we don't get a diff and it's very hard to review

2020-10-15 09:24 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.v
> +  // when the counter is on , all these staff are also locked
what does this comment mean?

2020-10-15 09:24 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.v
> +     ,.mem_cmd_i(loopback_cmd_li[0+:uce_mem_msg_width_lp])
why is this width mismatch occurring?

2020-10-15 09:25 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.v
> +      bp_me_cache_slice_stream
I don't see this module in the PR?

2020-10-15 09:27 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.v
> +module bsg_locking_arb_fixed_new #( parameter inputs_p="inv"
Can just point the submodule to your basejump_stl branch with this module

2020-10-15 09:28 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.v
> +  bp_uce_stream
I think you need to update the no_l2 case as well, with the stream2burst module

2020-10-15 09:29 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.v
> +  wire dcache_uce_resp_lock_li = proc_resp_lock_li[1] & proc_resp_v_li[1];
Shouldn't have to gate with resp_v_li, right? Lock should only be high when the stream is valid

2020-10-17 00:17 UTC, Songchun-Li commented
I was working on the other branch to implement the stream design with the pumps, so the latest work is not in this PR. I will rebase this branch to the last change I made soon.

2020-10-17 04:27 UTC, Songchun-Li commented
I've pushed my work of implementing bp_stream with pumps at two sides here, where I got the last benchmark, except the locking arbiter is removed from the unicore file. (I ran the tests again to make sure it is good for review) 

However, as the work is based on another PR of pump modules, the work here is also based on the me_dev_feature_dmanoserial branch. Should I change the merge target to me_dev_feature_dmanoserial rather than me_dev?

2020-10-22 02:23 UTC, Songchun-Li commented
This PR is rebased to the latest pump modules update. It is tested and is ready for review.

2020-11-20 02:32 UTC, Songchun-Li commented
Change to used the original locking arbiter with the change of last signal in the stream pumps. Passed cache hammer and riscv tests, and is ready for review

2020-12-28 09:52 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +    , localparam block_width_lp = `BSG_MAX(icache_block_width_p, dcache_block_width_p)
This is == cce_block_width_p, just use that

2020-12-28 09:55 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_burst_to_stream.sv
> +   , parameter in_data_width_p  = "inv"
Assume in == out and remove all buffering from this module

2020-12-28 09:55 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +   , parameter in_data_width_p  = "inv"
Assume in == out and remove all buffering from this module

2020-12-28 09:57 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +  if (icache_fill_width_p != dcache_fill_width_p)
This seems strange. Why would we need to rotate the return data in this case?

2020-12-28 10:04 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      mask_shift_amt_li = mem_cmd_stream_addr_lo[byte_offset_width_lp+:lg_cache_data_size_in_bytes_lp] << 3;
We only allow misaligned requests.  I think this block is handling the more general case of misaligned requests

2020-12-28 10:05 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +  if (icache_fill_width_p != dcache_fill_width_p)
Possibly due to misaligned request handling as commented above?

2020-12-28 10:07 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.sv
>        bsg_two_fifo
I think we wanted to get rid of these fifos? We'd need the UCE mem interface to be ready_and instead of ready_then, which should be fine.

Probably another PR, but I'm leaving this comment to remember

2020-12-28 10:09 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.sv
> +    bp_bedrock_uce_mem_msg_s io_resp_lo;
Why do we need this fifo, if the output interface is helpful?

2020-12-28 10:09 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.sv
> +   cmd_locking_arb_fixed_new
just cmd_arb

2020-12-28 10:11 UTC, dpetrisko requested changes
Looks really cool. Major comment is to rework burst2stream to remove buffering, some clarification and simplification requested in cce_to_cache

2020-12-29 22:14 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_burst_to_stream.sv
> +   , parameter in_data_width_p  = "inv"
The sipo/piso are removed from these modules. Should I remove the one_fifos as well?

2020-12-30 04:18 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +  if (icache_fill_width_p != dcache_fill_width_p)
![image](https://user-images.githubusercontent.com/26761214/103329455-9c2c9900-4a11-11eb-8c39-c79b4885cc5b.png)
I found a issue in l1_hetero where icache_block_width == icache_fill_width == 128 and dcache_block_width == dcache_fill_width == 256. In this case, cache_data_width == 256, and the 128-bit icache_block can be either halves of the 256 bits data, which is identified by the mask (0000_ffff or ffff_0000)in cache_pkt.
And  the returned data should be shifted right when the requested data is at the upper half (ffff_0000)of the 256 bits. (Highlited with the red line in the screenshot)

2020-12-30 08:19 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      mask_shift_amt_li = mem_cmd_stream_addr_lo[byte_offset_width_lp+:lg_cache_data_size_in_bytes_lp] << 3;
The reason I added this logic is to handle the more general case of misaligned requests is that there are many misaligned write requests into memory with the size of 64 bits or 32 bits (less than the bus size when fill_width > 64), when the instruction is loaded at initialization.
The following screenshot shows an example whose cache_data_width == 256 bits and 64 bits instructions are loaded. The 1 bits (set_mask) are left shifted to the corresponding position to store instructions.  
![image](https://user-images.githubusercontent.com/26761214/103338751-3b628800-4a34-11eb-81d9-3960cc548e85.png)

2021-01-01 18:12 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +  if (icache_fill_width_p != dcache_fill_width_p)
use bsg_bus_pack

2021-01-01 18:14 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_burst_to_stream.sv
> +   , parameter in_data_width_p  = "inv"
yep

2021-01-01 18:15 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +  bsg_one_fifo
these need to be two fifos in order to prevent bubbles

2021-01-01 18:17 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +              lg_cache_data_size_in_bytes_lp'(2): cache_pkt.data = {2{mem_cmd_data_lo[0+:(cache_data_width_p/2)]}};
The data should already be replicated on the mem_cmd bus.  If not, use bsg_bus_pack in the UCE

2021-01-01 18:20 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +  assign in_msg_ready_and_o = streaming_r ? data_ready_lo : header_ready_lo;
You can't accept a new header if data isn't ready. Need to &

2021-01-01 18:22 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_burst_to_stream.sv
> +      assign is_last_cnt = out_msg_v_o;
Is this clause needed for functionality, or are you optimizing out the counters?

2021-01-01 18:25 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            case(mem_cmd_header_lo.size)
You can just assign it, cache_pkt.mask is not checked for explicitly sized operations

2021-01-01 18:26 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +            state_n = (mem_cmd_done & index_done & way_done)
Is done and-ed with mem_cmd_v_o in the stream_pump module?

2021-01-04 23:04 UTC, Songchun-Li commented on bp_me/src/v/cce/bp_uce.sv
> +            state_n = (mem_cmd_done & index_done & way_done)
Yep

2021-01-05 00:31 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_burst_to_stream.sv
> +      assign is_last_cnt = out_msg_v_o;
The counters are needed only when block_width > bus_width (stream_words_lp>1), so we need counters to generate  sub-block address and to track the progress to generate last_o signal. I think this if clause would optimize the area when the counters are not necessary

2021-01-05 04:20 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +              lg_cache_data_size_in_bytes_lp'(2): cache_pkt.data = {2{mem_cmd_data_lo[0+:(cache_data_width_p/2)]}};
The data replication is actually for instruction data loading from the I/O port and have nothing to do with the UCE, so I used bsg_bus_pack for mem_cmd_data in the cce_to_cache

2021-01-05 05:44 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            case(mem_cmd_header_lo.size)
I understand that cache_pkt.mask is always 8'hff when cache_data_width == 64, so we can always assign it to '1. However, the question I have is, when cache_data_width > 64, for example, 128, the mask should be 16'hxxxx, right? For cache block load/store cmd from UCE, it is 16'hffff because it makes full use of the data width. However, when the instruction data is stored into L2 from the I/O initially, it got stored in size of 64 bits or 32 bits sometimes. In this case, the mask should be 16'h00ff or 16'hff00, and this is the reason I make it checking the size

2021-01-12 05:27 UTC, Songchun-Li commented on bp_top/src/v/bp_unicore.sv
> -  assign cache_cmd = '{header: cache_cmd_li.header
@dpetrisko This conversion leads to width mis-matches because the  cache_cmd/resp_data_width of l2_cache_slice and stream2burst are both uce_mem_data_width_lp, rather than cce_block_width_p. I think the conversion logic here should be removed, right?

2021-01-12 13:24 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.sv
> -  assign cache_cmd = '{header: cache_cmd_li.header
yep, can be removed

2021-01-12 13:39 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_burst_to_stream.sv
> +  assign out_msg_data_o = has_data ? data_lo : '0; // prevent meanless data from fifo.
don't gate data that already has a valid signal, it's just extra hardware

2021-01-12 13:41 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +  bsg_two_fifo
Similar to above, just header fifo

2021-01-12 13:42 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_burst_to_stream.sv
> +  bp_bedrock_out_msg_header_s out_header_lo;
This can be reduced to the single header buffer and passing through the data signals

2021-01-14 07:53 UTC, Songchun-Li commented
The data fifo in burst_to_stream has been removed, but I think it may not be reasonable to remove the data fifo in stream_to_burst.

`in_msg_ready_and_o` of stream_to_burst is connected to the cmd arbiter, and it is demanded by the arbiter. Therefore, the `in_msg_header_i` and `in_msg_data_i` only holds for 1 cycle when they are granted. If there is a fifo for header and no fifo for data, when the header is valid on the burst side, the data signal is already changed. Therefore, I think a buffer for data is necessary to hold the data for extra cycles. Or should I add a parameter, `ready_then_valid_p`, and generate the dafa_fifo when `ready_then_valid_p == 1`?

And I added a alternative solution in [bp_stream_to_burst_nofifo](https://github.com/black-parrot/black-parrot/pull/612/commits/2e9a30e24dd20c4629e4aed56933d51fff25901e#diff-f9622fbb9c13b85d03554a6e38bc2de068fa6a799cf94c366f90fc8deae19956), where both the header fifo and data fifo are removed. The cons. is that both `out_msg_header_ready_and_i` and `out_msg_data_ready_and_i` become demanding.

2021-01-26 03:36 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +    begin: hetero_l1_fill_width
Just always use bus_pack. I know it works in the case of homo l1, but as long as mem_resp_data_width > cache_data, we should use it.

(as an aside, I think bsg_bus_pack supports data_i > data_o width, but I'm not sure. If it doesn't it should be extremely quick to fix)

2021-01-26 03:38 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +    , output logic                                   mem_resp_ready_o
Make as many of these ready_and as possible, most of the yumis can be converted. I see there are some intermediate yumi signal names connected to ready_and_ports, which can be cleaned

2021-01-26 03:41 UTC, dpetrisko requested changes
Minor changes requested, but mostly I just need to look closer at the arbitration logic in the unicore. I think it's right, but it's a little complex and I need wrap my head around it.

Removing buffering in the conversion modules is the real blocker here

2021-01-26 06:22 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +    begin: hetero_l1_fill_width
The conditional generate statement here is removed.
 And I add some changes on the size_i signal. The reason is when `fill_width < block_width`, `size` in the resp header which is equal to block size, is larger than cache_data_width_p, then crash the mux output in the bsg_bus_pack.

2021-01-26 22:31 UTC, Songchun-Li commented on bp_me/src/v/cce/bp_uce.sv
> +    , output logic                                   mem_resp_ready_o
Shall I also replce the yumis with ready_and at the L2 sides? Or just the UCE side?

2021-01-26 22:40 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +    , output logic                                   mem_resp_ready_o
L2 too

2021-01-27 21:14 UTC, Songchun-Li commented on bp_top/src/v/bp_unicore.sv
> +  wire resp_arb_unlock = |({loopback_resp_yumi_li, cache_resp_ready_and_li, io_resp_yumi_o, clint_resp_yumi_li, cfg_resp_yumi_li} & {loopback_resp_v_lo, cache_resp_last_lo, io_resp_v_i, clint_resp_v_
Shall I take care of the other yumi besides cache cmd/resp ?

2021-02-22 16:24 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.sv
> +  wire resp_arb_unlock = |({loopback_resp_yumi_li, cache_resp_ready_and_li, io_resp_yumi_o, clint_resp_yumi_li, cfg_resp_yumi_li} & {loopback_resp_v_lo, cache_resp_last_lo, io_resp_v_i, clint_resp_v_
No, it's fine. Out of scope for this PR

2021-03-03 09:28 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cache_slice_stream.sv
> +
Replace bp_me_cache_slice.sv with bp_me_cache_slice_stream.sv, no need to keep the obsolete version around

2021-03-03 09:30 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            mem_cmd_ready_and_li = cache_pkt_v_o;
ready_and can't depend on a v_o signal, should be equal to cache_pkt_ready_i I think

2021-03-03 09:32 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            cmd_state_n = (mem_cmd_stream_new_lo & mem_cmd_ready_and_li) ? e_cmd_stream : e_cmd_ready;
ready_and_li & v_lo?

2021-03-03 09:33 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +  bsg_dff_en_bypass
I think we only need to save the address here, not the entire header. Same with burst_to_stream

2021-03-03 23:16 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            cmd_state_n = (mem_cmd_stream_new_lo & mem_cmd_ready_and_li) ? e_cmd_stream : e_cmd_ready;
mem_cmd_stream_new_lo is ANDed from v_lo within the stream_pump_in. Shall I remove the v_lo from the new_lo signal in the stream_pump, or shall I add a duplicated v_lo here to make it 
`mem_cmd_stream_new_lo &  & mem_cmd_v_lo & mem_cmd_ready_and_l`

2021-03-03 23:21 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            cmd_state_n = (mem_cmd_stream_new_lo & mem_cmd_ready_and_li) ? e_cmd_stream : e_cmd_ready;
oh let's remove it from stream pump, it's more standard to have them be independent

2021-03-03 23:24 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +  bsg_dff_en_bypass
I made some changes in the conversion mdules with what I learnt in the other PRs. 

-  In the stream_to_burst, the header buffer is removed and both header and data are passed through, as only the msg_type is used and it remains the same in all headera within a stream transcation.
- In the burst_to_stream, the header 2 fifo is replaced with a bypass register, as we need to hold the header from burst (last for a cycle only), to keeping sending header with different address to the stream side. And this change saves a cycle for each transcation.

2021-03-04 08:34 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cache_slice_stream.sv
> +
The obsolete version is removed, and the stream version is adopted with lite2stream and stream2lite in bp_tile and bp_l2e_tile.

2021-03-10 05:02 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +    end
This piece of code is added to handle data and mask of cache_pkt, when writeback data size is less than cache_data_width_p.

For example, if icache_fill_width == 256 and dcache_fill_width == 128, the cache_data_width == 256. When dcache writes back a dirty data block to L2, the 128 bits data can be either lower half of upper half of the 256 bits data in the cache_pkt. In current design, mask is set to be all 1s for SM op, so that the other half data will be overwritten mistakenly. Therefore, I added this logic to generate proper mask and data for this partial SM operation.

In fact, there is no cfg (icache_fill_width < dcache_fill_width ) now using this logic, and it is just an initiative for potential issue. I am not sure if it's worthwhile to support it.

2021-03-10 05:19 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +    end
```
  localparam bp_proc_param_s bp_unicore_l1_hetero_override_p =
    '{icache_sets         : 256
      ,icache_assoc       : 2
      ,icache_block_width : 128
      ,icache_fill_width  : 128
      ,dcache_sets        : 128
      ,dcache_assoc       : 4
      ,dcache_block_width : 256
      ,dcache_fill_width  : 256
      ,default : "inv"
      };
```

Does this config trigger these conditions?

2021-03-10 05:26 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +    end
Nope, because icache does not writeback. In this cfg, it reads all 256 bits data and `resp_data_bus_pack` is in charge of copying the upper half 128 bits data to the lower 128 bits half based on the address.

2021-03-10 05:34 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +    end
We certainly should support it though

2021-03-12 04:11 UTC, dpetrisko requested changes
Thanks! Looking really good. Clarifying questions and minor changes requested

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      localparam lg_dword_mask_width_lp=`BSG_SAFE_CLOG2(cache_data_width_p/dword_width_p);
I feel like a dword is a red herring, surely block_size_in_fill is more relevant?

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            mem_cmd_ready_and_li = cache_pkt_v_o;
This is weird. Shouldn't have a ready driven by a v_o

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +            mem_cmd_ready_and_li = cache_pkt_v_o;
Haven't looked too closely, but possibly:
- mem_cmd_ready_and_li = cache_pkt_ready_li
- cache_pkt_v_o = mem_cmd_ready_and_li & mem_cmd_v_lo

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.sv
> +            mask_len_width_lp'(4):  sel_mask = {data_len_width_lp{1'b1}} >> 2;
Should use a for loop so this is generalizable

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.sv
> +      // Generate proper wrap-around address for differenct incoming msg size dynamically,
differenct -> different

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.sv
> +      // stream_cnt are overriden depending on the size.
I'm still very confused by this logic. I'm sure it's right, but can you add ASCII art of how this works in practice?

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.sv
> +          mem_header_cast_o.addr = { fsm_base_header_cast_i.addr[paddr_width_p-1:stream_offset_width_lp+data_len_width_lp]
Nice! I like how much simpler this got

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +   , parameter out_data_width_p = in_data_width_p
Add an assertion that in_data_width_p == out_data_width_p

2021-03-12 04:11 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_burst.sv
> +   , parameter out_data_width_p = in_data_width_p
same for burst_to_stream

2021-03-12 04:11 UTC, dpetrisko commented on bp_top/src/v/bp_unicore.sv
> +   resp_locking_arb_fixed_new
resp_locking_arb_fixed_new -> resp_arb

2021-03-14 01:32 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cache_slice.sv
>   #(parameter bp_params_e bp_params_p = e_bp_default_cfg
The cache slice is removed, and I did not make much changes to the dma ports, not sure if I should simplify those, like the "unused" dma_mem_resp_header and its handshake

2021-03-15 04:00 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      wire [`BSG_SAFE_CLOG2(mask_sel_mux_els_lp)-1:0] cache_pkts_mask_sel_li = mem_cmd_header_lo.size - 2'h3;
This piece of logic is an variation of the logic in [bsg_cache](https://github.com/bespoke-silicon-group/basejump_stl/blob/3d85eefce4bfa815ab796f29b986e3c327e9b3dd/bsg_cache/bsg_cache.v#L684). The difference is that, in bsg_cache, the minimum size is byte and the maximum is dword, and here, the minimum here is dword.

Therefore, mem_cmd_header_lo.size gives size by 2^x bytes, however, the minimum unit here is dwords (8 bytes), therefore we have get the sizes by 2^(x-3) dwords  here to select corresponding mask.

In fact, I was thinking about adding this larger size opcode support to the bsg_cache, like LQ/SQ(quad_word) for 128 bits, but not sure if it is a good idea.

2021-03-15 04:06 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      wire [`BSG_WIDTH(`BSG_SAFE_CLOG2(cache_data_width_p/dword_width_p))-1:0] mem_cmd_size_li = `BSG_MIN(mem_cmd_header_lo.size - 3'h3, `BSG_SAFE_CLOG2(cache_data_width_p/dword_width_p));
Yes, the data is always in lower bits, but it is replicated here because sometimes the data should be at higher bits for memory store. For example, when dcache_fill_witdh == 128 and cache_data_width == 256, the store data can be
```
data: 128 bits data, 128'h0
mask: 16'hffff, 16'h0
```
or
```
data: 128'h0, 128 bits data
mask: 16'h0, 16'hffff
```

2021-03-15 06:50 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      wire [`BSG_WIDTH(`BSG_SAFE_CLOG2(cache_data_width_p/dword_width_p))-1:0] mem_cmd_size_li = `BSG_MIN(mem_cmd_header_lo.size - 3'h3, `BSG_SAFE_CLOG2(cache_data_width_p/dword_width_p));
Similarly, by adding ops LQ/SQ(quad_word) into bsg_cache makes the codes here look much cleaner.

2021-03-15 07:05 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      localparam lg_dword_mask_width_lp=`BSG_SAFE_CLOG2(cache_data_width_p/dword_width_p);
Indeed, using fill_width is more relevant, because using the minimum fill_width as the base unit in this loop-generated logic also save the area and power when the minimum fill width > dword, but it may be more difficult for coding.

2021-03-15 07:08 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_out.sv
> +      // stream_cnt are overriden depending on the size.
Here is simplified a lot with comments added!

2021-03-15 07:29 UTC, dpetrisko commented on bp_top/src/v/bp_l2e_tile.sv
> +      bp_me_cache_slice
Remove cache slice

2021-03-15 07:29 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cache_slice.sv
>   #(parameter bp_params_e bp_params_p = e_bp_default_cfg
delete the file so it's not accidentally in use (like in l2e tile)

2021-03-15 07:31 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +      localparam lg_dword_mask_width_lp=`BSG_SAFE_CLOG2(cache_data_width_p/dword_width_p);
I think using SM for all stores will simplify the logic with very little / no overhead

2021-03-15 07:41 UTC, Songchun-Li commented on bp_top/src/v/bp_l2e_tile.sv
> +      bp_me_cache_slice
It's been removed already, you should be able to see it with all the commits

2021-03-15 07:45 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cache_slice.sv
>   #(parameter bp_params_e bp_params_p = e_bp_default_cfg
It's been removed already, you should be able to see it with all the commits. And I also tested the multicore_1/2_l2e_cfg

2021-03-19 04:35 UTC, Songchun-Li commented
The mentioned issues are all resolved and the partial sm logic is also simplifed. 

And to test this logic, I wrote a new test, cache_dword_hammer [here](https://github.com/Songchun-Li/bp_tests/blob/dev_cache_dword_hammer/src/cache_dword_hammer.c), which load/store on the lowest dword of every cache block in the D-cache.  

I also test it with a new l1_hetero cfg as following, so that the dcache fill_width is less than the l2 data width and the condition statement is triggered.
```
icache_sets         : 128
,icache_assoc       : 4
,icache_block_width : 256
,icache_fill_width  : 256
,dcache_sets        : 256
,dcache_assoc       : 2
,dcache_block_width : 128
,dcache_fill_width  : 128
```

Above 2 features are just used in testing and not added to this PR yet. Let me know if I should add any of them.

2021-03-24 10:32 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +  if ((min_fill_width_lp > dword_width_p) && (min_fill_width_lp < cache_data_width_p))
Just use SM for all store operations

2021-03-24 10:33 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +          if (i == data_sel_mux_els_lp-1)
The else here should degenerate to '1, no?

2021-03-24 10:39 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +   #(.width_p(cache_data_width_p)
This should always be the mem_resp data width to comply with the interface. You could either pad the cache data with 0 or modify bus_pack to have input_width_p and output_width_p parameters

2021-03-24 10:39 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +   ,.unit_width_p(8))
omit default setting

2021-03-24 10:44 UTC, dpetrisko commented
@Songchun-Li Minor fixes.  Need to rebase on me_dev for cache_dma changes.  Otherwise I think we can start merging this in. 

There are going to be some conflicts with this other arbitration-related PR: https://github.com/black-parrot/black-parrot/pull/805/files, so we'll have to think about how this affects the stream pump in particular

2021-03-26 23:54 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.sv
> +  if ((min_fill_width_lp > dword_width_p) && (min_fill_width_lp < cache_data_width_p))
```
localparam lg_cache_size_in_fill_lp =`BSG_SAFE_CLOG2(cache_size_in_fill_lp);
localparam data_sel_mux_els_lp = lg_cache_size_in_fill_lp+1;
``` 
The main issue is when cache_size_in_fill_lp == 1, data_sel_mux_els_lp == 2 because of th bsg safe clog2. By replacing it with clog2, the special case here is reomved.

2021-03-27 00:06 UTC, Songchun-Li commented
For new, it passes weird config regression with multi-core cfg with the lite2stream conversion. Working on some port-width mismatches issus. 

Besides,  config like l1_wide and l1_tiny has minimum fill_width (bank width) larger than 64 bits, but l2_data_width is restricted to 64 bits in the if_verif, how should I handle this issue? @dpetrisko

2021-04-03 06:58 UTC, Songchun-Li commented
Hi @dpetrisko! The commits are rebased to the latest me_dev. All the issues mentioned or found are resolved. It passes regress tests including icache, dcache, me, weird cfg, and all different unicore cfgs running riscv_testslist with different fill width varying from minimum fill width to block width. It's now ready for final review. Lmk if you have any suggestion on bp_common_aviary_pkgdef.svh.

2021-04-03 22:14 UTC, dpetrisko commented on bp_top/syn/Makefile
> +export CFG   ?= e_bp_unicore_cfg
keep as default

2021-04-03 22:15 UTC, dpetrisko commented on bp_top/test/common/bp_nonsynth_if_verif.sv
> +  // if (icache_fill_width_p != dcache_fill_width_p)
Keep assertion and remove comment

2021-04-03 22:16 UTC, dpetrisko commented
Thanks! Okay I'm going to merge this into the stream pump branch and start bringing things over to mainline. I'll let you know if there are any changes needed once I'm looking at the true diff

2021-04-03 22:17 UTC, merged