BP Stream pump modules update
black-parrot/black-parrot pull request #622
Opened 2020-09-23 00:29 UTC by Songchun-Li

This pull request contains 3 major updates:
1. _bp_stream_pump_in_ and _bp_stream_pump_out_ are attached to _bp_cce_to_cache_new_. And the FSM and relevant logic in the _bp_cce_to_cache_new_ is updated to work with pumps.
2. _bp_lite_to_stream_ is updated according to the update of BP Stream protocol, including no lock for signal beat cmd/resp and no lock for the last packet in a sequence of cmds/resps.
3. _bp_cache_slice_new_ replaces the old one in _bp_unicore_, and the memory interface of _bp_unicore_ is updated. Also, _bp_burst_to_lite_ and _bp_lite_to_stream_ are added and used to connected _bp_unicore_ in the wrapper.

The PR passed riscv_testlist for fill_width=512, and is currently running beebs_teslist.

Note. _e_bp_unicore_no_l2_cfg_ is not yet updated with the new _bp_unicore_ memory interface.

2020-09-23 05:18 UTC, Songchun-Li commented
It also pass beebs_testlist

2020-09-23 08:04 UTC, dpetrisko commented
Please do the following to clean up the diff:
- rename _new modules to replace old modules directly
- rebase on me_dev
- checkout the new burst converters from me_dev and use those

2020-09-24 18:18 UTC, Songchun-Li commented
It has been rebased on me_dev and updated with the burst to lite logic on me_dev. And the _new modules replaces the old ones as well. It passed both riscv and beebs testlist

2020-09-24 19:36 UTC, dpetrisko commented on bp_top/syn/flist.vcs
> +$BP_ME_DIR/src/v/stream_pump/bp_stream_pump_in.v
Move these to /wormhole

2020-09-24 19:36 UTC, dpetrisko commented on bp_top/src/v/bp_tile.v
> +      bp_me_cache_slice_new
This should just be cache slice, right?

2020-09-24 19:36 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_to_lite.v
> +    //  if (mem_yumi_i)
undo

2020-09-24 19:37 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +
undo

2020-09-24 19:37 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +  wire [data_len_width_lp-1:0] num_stream_cmds = num_stream_cmds_1base - 1'b1;
undo, the -1 is more clear in len

2020-09-24 19:37 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +     ,.yumi_i(mem_v_o & mem_ready_i)
undo, ready & valid is more standard

2020-09-24 19:38 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +  logic [data_len_width_lp-1:0] data_cnt;
I think you just want to take my changes here as well.  Doing a count + add does not handle the wraparound case properly

2020-09-24 19:41 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.v
> +  // A new version of the stream fifo
delete comment, this won't make sense after being merged

2020-09-24 19:42 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cache_slice.v
> +
Add 

TODO: convert ports to stream interface to avoid ser/des

2020-09-24 19:43 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.v
> +            cache_pkt_v_o  = cache_pkt_ready_i & mem_resp_ready_lo & mem_cmd_v_lo;
don't need to wait for mem_resp_ready here.  The cache will stall if it's not ready at the output

2020-09-24 19:44 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.v
> +  assign address_offset = mem_cmd_cnt_lo << fill_offset_width_lp;
Should be able to just inject the stream cnt with the correct offset, rather than doing an addition.  See how it's done in the lite2stream module

2020-09-24 19:47 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.v
> +            cmd_state_n = mem_cmd_done_lo ? e_cmd_ready : e_cmd_stream;
does done raise high on the last entry or after the last entry has been sent?

2020-09-24 19:54 UTC, dpetrisko commented on bp_me/src/v/stream_pump/bp_stream_pump_out.v
> +  , input                                      new_i
I don't think the new_i signal is useful here, since we'll know if it's new from the fsm

2020-09-24 19:55 UTC, dpetrisko commented on bp_me/src/v/stream_pump/bp_stream_pump_out.v
> +  wire is_block_read  = header_cast_i.msg_type inside {e_mem_msg_rd};
uncached ops and regular ops can both be 1-512 bytes.  To see if it's a stream operation or not, you have to look at data size

2020-09-24 19:55 UTC, dpetrisko commented on bp_me/src/v/stream_pump/bp_stream_pump_out.v
> +    );
as above, concatenate rather than add

2020-09-24 20:00 UTC, dpetrisko commented on bp_me/src/v/stream_pump/bp_stream_pump_in.v
> +  , output logic [mem_msg_header_width_lp-1:0] header_o
probably makes sense to split out into 'base_header' and address_o.  That way, don't have to do the address recalculation repeatedly.  Same comment for pump out

2020-09-24 22:02 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.v
> +            cmd_state_n = mem_cmd_done_lo ? e_cmd_ready : e_cmd_stream;
Done signal is sent from the pump out when the the last entry has been sent, so the FSM here can simply transit back to ready when it gets a done pulse.

2020-09-24 23:21 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +  logic [data_len_width_lp-1:0] data_cnt;
But it seems there is some issues with the logic 
`last_cnt  = first_cnt - 1'b1;`
It stalls when it works with uncache commands with only 64 bit data

2020-09-24 23:32 UTC, Songchun-Li commented on bp_me/src/v/stream_pump/bp_stream_pump_out.v
> +  , input                                      new_i
The idea of new here is that it inducates the upcoming header will do stream. And those headers with data less than cache_data_width do not have high new_i signal. Indeed, we can work with the size info in header to identify if it will do stream, but the new signal is simply passed from the pump_in module and does not add much hardware overhead.

2020-09-25 00:02 UTC, Songchun-Li commented on bp_me/src/v/stream_pump/bp_stream_pump_in.v
> +  , output logic [mem_msg_header_width_lp-1:0] header_o
Probably a good idea for pump_in module, then the cnt_o is not necessary. However,it may not for the pump_out module.  At UCE side, we will need the cnt_o to fetch data from dirty_data_r and calculate the address for each entry for the very first time. And at L2 side, the FSM sends only the data from bsg_cache to pump_out and not does not provide any address info, so the pump_out have to recalculate the address.

2020-09-25 04:17 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +  logic [data_len_width_lp-1:0] data_cnt;
For example, when the uncached write 64 bit data into with address 0x8000_0000, we get the first-cnt of 0, then with -1 we have last_cnt of 0xf where the cnts are 4-bit-wide, but it should be 1 in fact.

2020-09-25 05:46 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +  logic [data_len_width_lp-1:0] data_cnt;
The latest commit basically picks up your changes and add something to solve some issues I saw in simulation. The remainning issue is to generate the different last_cnt based on size info.

2020-09-25 16:24 UTC, Songchun-Li commented on bp_me/src/v/cache/bp_me_cce_to_cache.v
> +  assign address_offset = mem_cmd_cnt_lo << fill_offset_width_lp;
Solved in the commit, "Change the address add to concatenate"

2020-09-27 04:37 UTC, Songchun-Li commented on bp_me/src/v/stream_pump/bp_stream_pump_out.v
> +    );
Solved in "Change the addr calculateion to concatenate in pump_out“

2020-09-28 05:26 UTC, Songchun-Li commented on bp_me/src/v/stream_pump/bp_stream_pump_out.v
> +  wire is_block_read  = header_cast_i.msg_type inside {e_mem_msg_rd};
Solved in the commit, "Make the pump module transists to stream states based on size info"

2020-09-28 07:30 UTC, Songchun-Li commented on bp_me/src/v/stream_pump/bp_stream_pump_out.v
> +  , input                                      new_i
Update: Removing the new_i should be helpful for decoupling the fsm and pump_out, and it is removed in the commit "Remove the new_i for pump_out"

2020-09-28 07:32 UTC, Songchun-Li commented
The mentioned issues are mostly fixed with a few commits, except the "address_o" one.

2020-10-02 04:51 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   // 1 : master: read is N to N, write is 1 to 1
Not sure I understand this designation, what does N to N mean here?

2020-10-02 05:03 UTC, dpetrisko requested changes

2020-10-02 05:03 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  assign last_cnt  = first_cnt - 1'b1;
again, I think last_cnt = first_cnt + the stream length

2020-10-02 05:03 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  assign last_cnt  = first_cnt - 1'b1;
same here

2020-10-02 05:03 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_cce_to_cache.v
>  module bp_me_cce_to_cache
This module looks great!

2020-10-02 21:47 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   // 1 : master: read is N to N, write is 1 to 1
For example, at master(UCE) sidem, for read operation, the pump_in receives N beats of headers/data and sends N beats of data to the UCE FSM. As for write operation, the pump_in receives 1 beat of write response and send 1 beat of write response to the FSM. This is how N to N and 1 to 1 come.
The interest part is at the client side, that we have 1 to N for read operation. That is because we sends one beat of cmd header to the pump_in, then pump_in decodes it and sends N beats of cmds to the L2 adapter FSM.

2020-10-03 18:54 UTC, Songchun-Li commented
There are 2 changes.
1. Replaced the cnt_o with stream_addr_o for the pump_in module like we discussed above. With this change, UCE and cce_to_cache will not need to repeatedly calculate the address, especially the address is demanding in multiple scenarios to fill the cache. It decouples the pump_in from fsm in a better way.
2. Changed the logic to get last_cnt for all three modules mentioned above, except the dff_en_bypass one as there is no special condition for the num_stream in the updated design any more
These changes passed cache_hammer, riscv_testlist and beebs, and it is ready for review.

2020-10-05 07:08 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   // 1 : master: read is N to N, write is 1 to 1
Makes sense that there should always be 1:1 correspondence between the FSM and the stream side.  Then I don't understand what you mean by having 1:N for reading.  You can't send more data into the stream than you get from the FSM...

2020-10-05 20:21 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   // 1 : master: read is N to N, write is 1 to 1
1:N for read and N:1 for write write response are about the header/addr and have nothing to do with data, and they happen only at the client side(cce_to_cache). 
For cache read, we have only 1 beat of command with critical address from the stream side, then pump_in decodes this command into 8 sub-block address (with 64 bit cache data width) and send it to cce_to_cache FSM, so we have 1:8 for read. As for write response, the pump_out waits for 8 response from FSM, and only sends out 1 response to the stream side, when all 8 responses is receive, so we have 8:1. As you can see, neither of them involves data.
I understand this maybe misleading and try to get a better way to describe it.

2020-10-05 22:33 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   // 1 : master: read is N to N, write is 1 to 1
I added some new comments in the latest commit.

2020-10-08 03:09 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +   //             write: combines N sub-block store responses from bsg_cache into 1 block store response, and sends it to stream side
bsg_cache should only be sending 1 store response for a burst store, per the stream specs

2020-10-08 03:13 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   , localparam block_offset_width_lp = `BSG_SAFE_CLOG2(cce_block_width_p >> 3)
This should be a parameter, not just cce_block_width_p

2020-10-08 03:13 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   , parameter cache_data_width_p = dword_width_p
Rename, not specific to cache

2020-10-08 03:15 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +   , parameter logic master_p = 1
Take a look at how bp_burst_to_lite et al handle the specialization.  It's more flexible and less confusing than this.   I think your master/client terminology is a bit off, but this should fix it anyway

2020-10-08 03:16 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic [mem_msg_header_width_lp-1:0] header_o
I'd name these fsm_* for clarity

2020-10-08 03:16 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic [paddr_width_p-1:0]           stream_addr_o
fsm_addr_o

2020-10-08 03:17 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +        e_pass_stream:
Comment what each of these states are doing.  I think pass_stream and decode_stream can be combined, since the only difference seems to be whether an ack is sent

2020-10-08 03:19 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +module bp_stream_pump_out
Similar comments to stream_pump_in

2020-10-14 17:49 UTC, Songchun-Li commented
The pump modules are changed with payload_mask_p and the pass/decode, pass/combine stream states are integrated. It passed cache_hammer, riscv and beebs testlist, and is ready for review.

2020-10-15 09:21 UTC, dpetrisko requested changes

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  wire is_read_op  = mem_header_lo.msg_type inside {e_bedrock_mem_uc_rd, e_bedrock_mem_rd};
is_read / is_write should be at best irrelevant and at worst incorrect with payload_mask_p

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_stream.v
> +  bsg_dff_en
Bump for this change

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  wire is_read_op  = fsm_header_cast_i.msg_type inside {e_bedrock_mem_uc_rd, e_bedrock_mem_rd};
same here, replace just with payload mask

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  enum logic [1:0] {e_reset, e_single, e_stream, e_combine_stream} state_n, state_r;
remove unused combine_stream state

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +        e_single:
I actually don't think you need this FSM at all.  The degenerate case of stream is a single data beat which doesn't have any special properties other than being length 1

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +        e_single:
Same here, I don't think we need an FSM, and instead reduce the single_beat case to be a stream of length 1

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic [paddr_width_p-1:0]           fsm_addr_o
put with the other FSM signals

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  , input        [bp_bedrock_xce_mem_msg_header_width_lp-1:0] fsm_header_i
fsm_base_header

2020-10-15 09:21 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic [bp_bedrock_xce_mem_msg_header_width_lp-1:0] fsm_header_o
fsm_base_header

2020-10-15 09:22 UTC, dpetrisko commented
Gave more feedback to simplify stream pumps

2020-10-20 18:38 UTC, Songchun-Li commented
Updates are made based on the above suggestions and it is ready for review.

2020-10-21 20:57 UTC, Songchun-Li commented
Found some issues in the pump_in when it is attached to UCE and got them fixed. The updated pump modules are tested.

2020-10-26 11:53 UTC, dpetrisko requested changes

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +      if (single_data_beat | (is_master & ~has_data))
I don't think you need this if statement

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +      if (single_data_beat | (is_master & ~has_data))
Same here, I think this is unnecessary

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +
mem_lock_o is undriven in this case

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  , input                                                     mem_yumi_i
We should convert this to mem_ready_and_i and fsm_ready_and_o.  That will be much more flexible

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic                                               mem_ready_o
We should convert this to mem_ready_and_o and fsm_ready_and_i. That will be much more flexible

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  bsg_dff_reset_en
bsg_dff_reset_set_clear

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic                               new_o
Maybe stream_new_o, stream_done_o is more clear?  new_o seems like it should be high even for single beat transactions

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +            new_o = '0;
Seems like there's a lot of overlap between new_o, done_o and lock.  

Could we just do fsm_lock_o, and then the transition would happen on raising and lowering of lock? I guess the issue is the last beat.  This is the problem with not having a "last" signal in the interface, I guess

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  bsg_dff_en_bypass
Do you need to save this separately? Isn't mem_header_lo valid for the entire stream transaction?

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +     ,.val_i(first_cnt + 1'b1)
I think you can simplify a lot of logic here with .val_i(first_cnt + cnt_up).  Then first_cnt == last_cnt for single beat transactions.  You'll still need the cnt_o bypass logic, though

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +    );
I think streaming is more simply == mem_v_lo & ~done_o?

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +     ,.val_i(first_cnt + 1'b1)
Similar comments to stream_pump_in

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  wire is_master = (payload_mask_p == mem_cmd_payload_mask_gp);
get rid of is_master

2020-10-26 11:53 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  wire is_master = (payload_mask_p == mem_resp_payload_mask_gp);
get rid of is_master

2020-10-26 21:30 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  bsg_dff_en_bypass
The tricky part is that the mem_header_lo is different betweem read commands and write commands at the L2 adapter side. For read commands, we receive only one cmd from stream side, so we can take it as the fsm_base_header_o directly. However, for write commands, we receive N cmds from the stream sides, so the critical_addr is saved to keep fsm_base_header_o the same. Otherwise, the addr in the fsm_base_header_o keeps incrementing.

2020-11-10 23:45 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic                               new_o
new_o is uesd in cce_to_cache as a transiting condition of jumping to stream state from ready state, so I think it should not be high for single beat transactions

2020-11-11 00:31 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +    );
The reason I use a register to hold this is because the new_o = fsm_yumi_i & ~streaming_r, is high only for the first cycle, so it can be used to set the counter and the registers holding the base addr. If we make streaming = 
 mem_v_lo & ~done_o, it will alyways be high before the done signal

2020-11-20 00:55 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  , input                                                     mem_yumi_i
mem_yumi_i is converted to mem_ready_and_i, but not sure if I did the right conversion for fsm_yumi_i because unlike other modules with ready_and_o I seen, there is no fifo in the pump out, so the fsm side has to be demanding

2020-11-20 02:31 UTC, Songchun-Li commented
Made the change of replacing lock signal with last signal and changes based on the feedback. Passed cache_hammer and riscv tests and is ready for review.

2020-11-22 09:11 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +    );
makes sense!

2020-11-22 09:14 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +    );
Oh, new_o = mem_v_lo & (stream_cnt == first_cnt) is lower hardware overhead.  It shouldn't depend on the fsm handshake i.e. new_o is 'helpful'

2020-11-22 09:15 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  );
Can get rid of this register, ready if cnt == '0

2020-11-22 09:18 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +          fsm_addr_o = { mem_header_lo.addr[paddr_width_p-1:stream_offset_width_lp+data_len_width_lp]
Does this work with fill_width == 512? I think this concatenation would break because stream_cnt should be 0 bits in that case

2020-11-22 09:18 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +  , output logic                                              done_o
minor; stream_done_o

2020-11-22 09:18 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  , output logic [data_len_width_lp-1:0]       cnt_o
minor; stream_cnt_o, stream_done_o

2020-11-23 03:27 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  );
Making ready = (cnt == '0) does not work in some cases when the critical word address is not aligned to the block, because cnt value after streaming is done can be non-zero. In addition, with a wrapped-around sequence, it is possible that cnt == 0 at the middle. In this case, stream_cnt will be set back to first_cnt because it rise the set_cnt signal.

2020-11-23 03:29 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +    );
I've make the stream_new_o to be helpful, but the given logic may not work because stream_cnt = stream_new_o ? first_cnt : current_cnt; so there is a loop here. Therefore, I also try to reset the counter with stream_done, so that we can have new_o = fsm_v_o & (current_cnt == '0), like your suggestion below for the ready signal. However, the issue prevents me from doing this.

2020-11-23 03:31 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +          fsm_addr_o = { mem_header_lo.addr[paddr_width_p-1:stream_offset_width_lp+data_len_width_lp]
Yep, it does not work with fill_width == 512. I was planning to make it support 64 bit for the first version and add the variable fill width support in the other PR, the bp_stream with locking arbiter one.

2020-11-23 05:31 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +          fsm_addr_o = { mem_header_lo.addr[paddr_width_p-1:stream_offset_width_lp+data_len_width_lp]
I'd rather have it support both here so we can merge it in without breaking anything.  I think it should be pretty straightforward using this: https://verificationacademy.com/forums/systemverilog/zero-bit-width-array

2020-11-23 06:20 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +          mem_last_o = 1'b1;
this whole clause is the same as has_data, can be combined

2020-11-23 06:26 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  );
I see your point.  Doesn't this start in a ~ready state?

2020-11-23 06:27 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +    );
Hm, let me think about this.  The 1-bit FSM might make more sense after all

2020-11-23 06:29 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +          fsm_addr_o = '0;
I think this can be combined with the below case

2020-11-23 06:29 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +          cnt_up = fsm_ready_and_i & fsm_v_o;
To combine, I think cnt_up = fsm_ready_and_i & fsm_v_o & ~is_last

2020-11-23 07:56 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +  );
ready_r was used in pump_out and streaming_r is used in pump_in. They are for the same purpose, but in opposite presentation, so I changed it to streaming_r in pump_out to make them consist in the last commit.And I agree to use a 1-bit FSM which should make more sense while solving this register issue.

2020-11-24 05:20 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_in.v
> +          cnt_up = fsm_ready_and_i & fsm_v_o;
This may not be a good idea. After running some tests, I found out when there is a wrapped around sequence, the stream_cnt can be any value after a stream_done and so does the last_cnt of the next sequence. If stream_cnt == last_cnt at the beginning, the counter will not cnt_up and mistakenly send out stream_done.

2020-11-24 07:16 UTC, Songchun-Li commented
Combine signals in the pump modules. Update the pump_in with 1-bit FSM. Any additional comments on the pump_in module? Still working on combining signasl and fsm update  in pump_out.

2020-11-25 00:22 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_stream_pump_out.v
> +      unique case (state_r)
It seems using 1-bit fsm in pump_out may not be a good idea sinc the 2 clauses are kind of parallel. @dpetrisko Do you have any suggestions?

2020-11-25 05:02 UTC, Songchun-Li commented
Add variable stream_data_width support including stream_data_width == 512 bit. Discard the 1 bit fsm change because using 1-bit reigster can be more flexible to work with stream_data_width from 64bit to 512 bit.

2020-11-26 19:33 UTC, dpetrisko approved these changes
Awesome!! Thanks for the iterations on this, the code looks great now

2020-11-26 19:33 UTC, merged