Fix cache late restart due to dirty data writeback
black-parrot/black-parrot pull request #655
Opened 2020-10-29 19:05 UTC by Songchun-Li

This PR includes 2 updates:
1. Change the cache_req interface between L1 cache and UCE from ready-then-valid to valid-then_yumi.
2. UCE sends cache_req_complete_o to L1 cache and then write back dirty data, so L1 cache can restart early.

The updates is test with cache_hammer, riscv_testlist and beebs testlist with full block size and sub-block size. A possible known issue is that the credits counter may overflow when fill_width_p==64. This issues results from the 8 credits for dirty data writeback may come back later than new credits issued by the next command, but this is no longer a concern if the when it is merged with the stream pump updates because it will only consume 1 credit.

2020-10-29 20:53 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  wire wt_miss_tv = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & cache_req_v_o & (writethrough_p == 1);
I think cache_req_v_o & ~cache_req_yumi_i?  Did you test this with a writethrough cache configuration?

2020-10-29 20:58 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  assign ready_o = ~cache_miss_r & ~(cache_req_v_o & ~cache_req_yumi_i);
Not quite.  This will make the cache be ready on boot, meaning we spend a ton of cycles just missing repeatedly while the cache engine isn't ready yet.  Instead, we should start quiescent and then send a cache_req_complete_i from the cache engine when it transitions to ready for the first time.  It's also probably not necessary to make the cache ~ready on a req_miss, since we'll be flushing the pipeline.  However, it's safer to leave it in, and we can take it out if it's timing critical

2020-10-29 20:58 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +                            | (uncached_tv_r & (decode_tv_r.store_op & ~(cache_req_v_o & ~cache_req_yumi_i)))
just cache_req_yumi_i

2020-10-29 20:59 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  wire flush_req = cache_req_yumi_i & (cache_req_cast_o.msg_type == e_cache_flush); // TOCHECK
this is right, remove comment

2020-10-29 21:00 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +    assign wbuf_success = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & ~decode_tv_r.l2_op & ~(cache_req_v_o & ~cache_req_yumi_i);
just cache_req_yumi_i

2020-10-29 21:00 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  assign tl_we = (vaddr_v_i | fencei_v_i) & ~cache_req_v_o & ~fencei_req;
Not sure if this is necessary

2020-10-29 21:01 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  wire vaddr_ready_o = ~cache_req_v_o & ~cache_miss;
this is an output port so it should be assigned, I'm surprised this doesn't break things

2020-10-29 21:02 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
> +    ,.clear_i(cache_req_complete_o | way_up | writeback_complete)
Shouldn't we take out cache_req_complete_o here?

2020-10-29 21:05 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
>    always_comb
This is a bit off.  The idea is that we can transition back to ready before the writeback is done, so that we can continue to service requests which don't require writeback (uncached requests).  So we need to extract the writeback_complete logic outside of the state machine / in the ready state.  

The cache_req_yumi_o signal should determine whether to yumi or not based on request type

2020-10-29 21:07 UTC, dpetrisko commented
>fill_width_p==64. This issues results from the 8 credits for dirty data writeback may come back later than new credits issued by the next command, but this is no longer a concern if the when it is merged with the stream pump updates because it will only consume 1 credit.

We shouldn't be sending out requests if credits are empty, and we shouldn't receive more credits than we allocate.  If there's an issue with the counting, that's a bug we need to fix or it could cause deadlock

2020-10-29 21:22 UTC, dpetrisko commented
Also, add these changes to LCE!

2020-11-05 00:24 UTC, Songchun-Li commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +    assign wbuf_success = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & ~decode_tv_r.l2_op & ~(cache_req_v_o & ~cache_req_yumi_i);
Replacing cache_req_ready_i with cache_req_yumi_i here causes loop. Given wbuff_success -> wbuf_v_li -> wt_req -> cache_req_v_o, and cache_req_yumi_i demands cache_req_v_o in the UCE, it gives a loop if wbuff_success demands cache_req_yumi_i

2020-11-05 00:30 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +    assign wbuf_success = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & ~decode_tv_r.l2_op & ~(cache_req_v_o & ~cache_req_yumi_i);
You’ll need to break the signal into multiple parts. The outgoing part will not depend on cache_req_yumi, but whether or not to put in the writebuffer will

2020-11-05 19:32 UTC, Songchun-Li commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  assign ready_o = ~cache_miss_r & ~(cache_req_v_o & ~cache_req_yumi_i);
A initial ready reg is added to keep quiescent before the cache engine is ready

2020-11-07 01:22 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  assign ready_o = ~cache_req_busy_i & ~cache_miss_r & ~(cache_req_v_o & ~cache_req_yumi_i);
don't need ~(cache_req_v_o & ~cache_req_yumi_i); here

2020-11-07 01:23 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
>      assign wbuf_success = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & ~decode_tv_r.l2_op;
double assigning wbuf_success?

2020-11-07 01:24 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  assign tl_we = (vaddr_v_i | fencei_v_i) & ~fencei_req;
~busy

2020-11-07 01:25 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  assign vaddr_ready_o = ~cache_req_busy_i & ~cache_req_v_o & ~cache_miss;
yumi, not v

2020-11-11 21:22 UTC, Songchun-Li commented
The changes are rebased to the me_dev and passes icache and dcache regress ci test. Ready for review

2020-11-14 00:38 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +      cache_req_v_o = 1'b1;
these can just be ~flush_i

2020-11-14 00:38 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +      cache_req_v_o = 1'b1;
this can just be ~flush_i

2020-11-14 00:49 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.v
> +  assign cache_req_yumi_o = cache_req_v_i & req_ready_lo & cmd_ready_lo & ~timeout;
cache_req_yumi_o = cache_req_v_i & ~cache_req_busy_o

2020-11-14 00:49 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.v
> +  // LCE's cache_req_yumi_o signal to prevent the cache from issuing a new request, thereby
busy_o

2020-11-14 00:49 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.v
> +      ,.cache_req_v_i(cache_req_v_i & req_ready_lo)
shouldn't need this.  The interface is ready->valid

2020-11-14 00:50 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.v
>        ,.cache_req_i(cache_req_i)
Should change the interface here to valid yumi as well

2020-11-14 01:25 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +    assign wbuf_success = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & ~decode_tv_r.l2_op & cache_req_yumi_i;
wbuf_success = wt_success for writethrough case

2020-11-14 01:55 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +      cache_req_v_o = gdirty_r & (l1_coherent_p == 0);
flush_i here too

2020-11-14 01:56 UTC, dpetrisko requested changes
Very close, minor changes requested

2020-11-16 01:57 UTC, Songchun-Li commented
Changes have been made based on the feedback and passed ci tests for cache

2020-11-16 02:19 UTC, dpetrisko requested changes

2020-11-16 02:19 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.v
this module should have both ready and yumi, otherwise we will get into an infinite miss loop situation when req is busy

2020-11-16 02:19 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  wire wt_req = wt_success & ~flush_i;
- get rid of wt_success
- wt_req = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & ~decode_tv_r.l2_op & (writethrough_p == 1) & cache_req_yumi_i;
- wbuf_success = wt_req

2020-11-16 04:38 UTC, Songchun-Li commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  wire wt_req = wt_success & ~flush_i;
We can not make wt_req dependent on cache_req_yumi_i, because wt_req -> cache_req_v_o -> cache_req_yumi_i and it gives a loop. And I added the wt_sucess to seperate the it from wbuf_success based on your feedback:

> You’ll need to break the signal into multiple parts. The outgoing part will not depend on cache_req_yumi, but whether or not to put in the writebuffer will

2020-11-16 04:57 UTC, Songchun-Li commented on bp_me/src/v/lce/bp_lce.v
So I should add ~req_ready_lo to cache_req_busy_o, right?

2020-11-17 21:13 UTC, dpetrisko commented on bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
> +  wire wt_req = wt_success & ~flush_i;
oh, got it.  

```
wt_req = v_tv_r & decode_tv_r.store_op & store_hit_tv & ~sc_fail & ~uncached_tv_r & ~decode_tv_r.l2_op & (writethrough_p == 1) & ~flush_i;

wb_success = wt_req & cache_req_yumi_i;
```

2020-11-17 21:14 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.v
yep, looks good to me

2020-11-17 21:15 UTC, dpetrisko requested changes
lgtm with the one line change in the D$

2020-11-17 21:16 UTC, dpetrisko commented
@muwyse can you give this a once over since it has LCE changes?

2020-11-17 22:33 UTC, Songchun-Li commented
wt_success has been removed from the dcache.

2020-11-17 22:50 UTC, dpetrisko approved these changes
Great!

2020-11-17 23:06 UTC, muwyse approved these changes
LGTM. I don't see anything that looks out of place in the LCE.

2020-11-17 23:19 UTC, merged