Tiny Instruction Cache
black-parrot/black-parrot pull request #669
Opened 2020-11-08 06:11 UTC by sripathi-muralitharan

This PR adds support for a tiny cache - 4KB and a corresponding tiny config (reflects only the tiny icache changes) that is supported only in the UCE. 

A similar change for the D$ will soon follow in a future PR.

2020-11-08 13:49 UTC, taylor-bsg commented
Nice work!

This is a lot of extra code to support a corner case.  Lot of it has to do with signal width underflow kind of conditions. Unfortunately, this means that meta programming is only partially working, and our code gets multiplied up exponentially with all of these cases.

My suggestion is that as much as possible you should try to push the underflow down into the leaf modules, so that they are more robust in general to this sort of thing, for example the LRU module or the stat ram. Then when we write other code that has underflow, it will just work out of the box. A simple example of this is the variable #input mux module, and making it handle the case of only one incoming item. In general we have created the macro BSG_SAFE_CLOG2 for underflow cases where only one item is there, and the CLOG2 function returns 0, results in a zero width signal. In this case we may need something like BSG_SAFE_MINUS.

M

2020-11-08 15:55 UTC, dpetrisko commented
^ took the words right out of my mouth

2020-11-12 20:05 UTC, sripathi-muralitharan commented
Opened a PR in Basejump-STL with this macro. PR 352 - https://github.com/bespoke-silicon-group/basejump_stl/pull/352. I hope this is sufficient to solve the meta programming problem here. 

I haven't made changes to the code in BP yet (Waiting for the one in Basejump-STL to be merged in)

2020-11-12 21:44 UTC, dpetrisko commented
You should make the changes, point the submodule to your basejump stl branch, and then write “depends on #xyz” as a comment here. That’s the best way to track these things

> On Nov 12, 2020, at 12:06 PM, sripathi_muralitharan <notifications@github.com> wrote:
> 
> ﻿
> Opened a PR in Basejump-STL with this macro. PR 352 - bespoke-silicon-group/basejump_stl#352. I hope this is sufficient to solve the meta programming problem here.
> 
> I haven't made changes to the code in BP yet (Waiting for the one in Basejump-STL to be merged in)
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-17 21:19 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  `declare_bp_cache_service_if(paddr_width_p, ptag_width_p, icache_sets_p, `BSG_MAX(2, icache_assoc_p), dword_width_p, icache_block_width_p, icache_fill_width_p, icache);
do the max(2) in the macro

2020-11-17 21:19 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +    `declare_bp_cache_service_if_widths(paddr_width_p, ptag_width_p, icache_sets_p, `BSG_MAX(2, icache_assoc_p), dword_width_p, icache_block_width_p, icache_fill_width_p, icache)
max(2) in macro

2020-11-17 21:20 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +    // They boil down to the same thing for a set associative cache
This comment is confusing -- instead, I would draw an ascii diagram

2020-11-17 21:22 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +    , localparam mem_bank_offset_width_lp = $clog2(icache_assoc_p)
having both bank_offset_width and mem_bank_offset_width is very confusing.  Why not just set bank_offset_width correctly?

2020-11-17 21:23 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  // For direct-mapped the LRU bits are unused. Constant propagation will
These comments about direct-mapped cache are unnecessary.  It's a very niche configuration

2020-11-17 21:25 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
>    bsg_mem_1rw_sync_mask_write_bit #(
@taylor-bsg Crazy idea, but does it make sense to support 0-width memories as well?

2020-11-17 21:29 UTC, dpetrisko commented
@taylor-bsg .  Most of the other corner cases are related to 0-width concatenations e.g. {index, offset}, where offset is 0 bits. I can't think of a good way to get around that

2020-11-17 21:35 UTC, taylor-bsg commented
Yeah I suggested to Sripathi that we support 0-width memories rather than a
separate generate statement.

BSG_SAFE_CONCAT ?



M

On Tue, Nov 17, 2020 at 1:29 PM Dan Petrisko <notifications@github.com>
wrote:

> @taylor-bsg <https://github.com/taylor-bsg> . Most of the other corner
> cases are related to 0-width concatenations e.g. {index, offset}, where
> offset is 0 bits. I can't think of a good way to get around that
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/black-parrot/black-parrot/pull/669#issuecomment-729225225>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEFG5ACZ5BPMU73FCPP3MUTSQLTLRANCNFSM4TODWN6Q>
> .
>

2020-11-17 21:47 UTC, dpetrisko commented
> BSG_SAFE_CONCAT

Hm, we need to signal to the macro if the field is actually a 0-width signal disguised as a 1-width signal `BSG_SAFE_CONCAT(index, offset) makes it ambiguous if offset is actually 0 or 1 bits.

`BSG_SAFE_CONCAT(index, offset, $clog2(offset)) would solve this problem but is a little messy.

2020-11-18 23:21 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.v
> +    , localparam mem_bank_offset_width_lp = $clog2(icache_assoc_p)
That's because when defining widths, I wanted them to be one so that I don't get bit vectors with negative indices. But for places where I want to index using the +:, I wanted a zero to be correct.

2020-11-19 03:28 UTC, sripathi-muralitharan commented
For BSG_SAFE_CONCAT, is it okay to enforce ordering in the parameters? Like the first parameter has to be something non-zero and the second one could be 0 or non-zero?

2020-11-19 18:15 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.v
> +    // They boil down to the same thing for a set associative cache
Got rid of one of them and reverted back to the previous state of only 1 offset parameter by leveraging BSG_SAFE_MINUS

2020-11-19 18:17 UTC, sripathi-muralitharan commented
Managed to solve the other 0-width concatenations issue by using a conditional concatenation feature in Verilog. Ready for review again.

2020-11-20 10:48 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
> +      assign fill_index_shift = (assoc_p > 1)
I think you can use the zero width concatentation here

2020-11-20 10:50 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
> +      assign fill_index_shift = mem_resp_cast_i.header.addr[byte_offset_width_lp+:`BSG_MAX(bank_offset_width_lp,1)] >> bank_sub_offset_width_lp;
Do you need the max here? If fill_size_in_bank == 1 for direct mapped, then this clause will never get called

2020-11-20 10:50 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
> +  // For direct-mapped caches, the fill width should be equal to block width
Is bank_width == block_width? I thought there was just an inequality there

2020-11-20 10:52 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
> +    , localparam bank_offset_width_lp  = $clog2(assoc_p)
If you keep this as SAFE_CLOG2 and use zero width concatentation, I believe that will get rid of all the edge cases below

2020-11-20 10:52 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_top.v
>     , localparam num_dwords_per_bank_lp = bank_width_lp / dword_width_p
I don't think any of these parameters are used?

2020-11-20 10:53 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +      stat_mem_data_li.lru = {(`BSG_MAX(2, icache_assoc_p)-1){1'b0}};
can just use '0 and '1

2020-11-20 10:53 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  logic [`BSG_MAX(2, icache_assoc_p)-2:0] lru_decode_data_lo;
bsg_safe_minus?

2020-11-20 10:53 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +        assign data_mem_addr_li[i] = tl_we
zero width concat

2020-11-20 10:54 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  assign cache_req_metadata_cast_lo.repl_way = (icache_assoc_p > 1)
goes away with zero width memory

2020-11-20 10:54 UTC, dpetrisko commented on bp_common/src/include/bp_common_cache_engine_if.vh
> +    logic [`BSG_MAX(ways_mp-2, 0):0] lru; \
safe minus

2020-11-21 01:49 UTC, sripathi-muralitharan commented on bp_me/src/v/cce/bp_uce.v
> +  // For direct-mapped caches, the fill width should be equal to block width
The general inequality is bank_width <= block_width. For the direct-mapped case, it becomes bank_width = block_width

2020-11-21 01:49 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_top.v
>     , localparam num_dwords_per_bank_lp = bank_width_lp / dword_width_p
Yes, there are some redundant parameters. I can get rid of them.

2020-11-21 03:09 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.v
> +  assign cache_req_metadata_cast_lo.repl_way = (icache_assoc_p > 1)
Not so sure about this. Seems to me that the priority encoder from where the `invalid_exist` and `way_invalid_index` are generated end up throwing out X's when width_p = 1. Seems to me that these corner conditions haven't been handled fully/correctly. This means, that will end up putting an X on the metadata way. I am guessing it may not become a problem since its all direct mapped and there is no concept of a way, but I am worried about the X-propagation that might cause issues down the line? What do you think about this?

2020-11-21 03:42 UTC, sripathi-muralitharan commented on bp_me/src/v/cce/bp_uce.v
> +    , localparam bank_offset_width_lp  = $clog2(assoc_p)
I believe that will not calculate some of the other parameters correctly. So, I think its best to keep it the way it is. But exactly which edge cases are you talking about? The ones with the indexed-part selects (eg. line 305 in `bp_uce.v`)?

2020-11-21 03:45 UTC, sripathi-muralitharan commented on bp_me/src/v/cce/bp_uce.v
> +      assign fill_index_shift = (assoc_p > 1)
Yup. Fixed that in the latest commit.

2020-11-24 02:56 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.v
> +  assign cache_req_metadata_cast_lo.repl_way = (icache_assoc_p > 1)
that means those leaf modules do not handle zero width signals correctly and should be fixed

2020-11-24 02:57 UTC, dpetrisko commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +  (`BSG_MAX(2, (2*ways_mp-1)))
nit, but do (safe_minus() + ways_p) to be explicit

2020-11-24 03:04 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
> +    , localparam bank_offset_width_lp  = $clog2(assoc_p)
pretty much everywhere bank_offset_width_lp is used below, it is with BSG_SAFE_MINUS or BSG_MAX.  If it's set to 1 up here, then those will go away.  

Better to adjust in the parameter calculation than in the datapath, for clarity

2020-11-24 03:05 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.v
> +  // For direct-mapped caches, the fill width should be equal to block width
This comment is kind of out of place, doesn't really say much about the below code.  I'd combine it with the below comment or just get rid of it

2020-11-25 09:18 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.v
> +  assign cache_req_metadata_cast_lo.repl_way = (icache_assoc_p > 1)
Fixed in basejump and opened a PR - https://github.com/bespoke-silicon-group/basejump_stl/pull/357

2020-11-25 09:22 UTC, sripathi-muralitharan commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +  (`BSG_MAX(2, (2*ways_mp-1)))
Tried to do it the way that was suggested, but doing a safe_minus returns a 0 which is not very useful for width calculations. To make things more explicit, I added in a ?: to switch between ways = 1 and ways != 1.

2020-11-25 09:52 UTC, dpetrisko commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +  (`BSG_MAX(2, (2*ways_mp-1)))
how it was originally was fine

2020-11-25 09:53 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +      // Setting fill_index_shift to zero for direct-mapped caches since there aren't any opportunities for iterative filling as well as no data memory banks
// fill_index_shift corresponds to the single bank in a direct-mapped cache

2020-11-25 09:54 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
>      , localparam byte_offset_width_lp  = `BSG_SAFE_CLOG2(bank_width_lp>>3)
Nice! I think this module is minimally modified

2020-11-25 09:54 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  assign stat_mem_o = (icache_assoc_p > 1) ? {stat_mem_data_lo.lru, icache_assoc_p'(0)} : '0;
don't need

2020-11-25 09:56 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +    wire [`BSG_SAFE_MINUS(bank_offset_width_lp, 1):0] data_mem_pkt_offset = (`BSG_MAX(1, bank_offset_width_lp)'(i) - data_mem_pkt.way_id);
I don't think you actually need this: a [-1:0] slice is perfectly legal, and with get removed below

2020-11-25 09:56 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  assign cache_req_metadata_cast_lo.repl_way = (icache_assoc_p > 1)
don't need conditional

2020-11-25 09:59 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  assign vaddr_offset     = (icache_assoc_p > 1) ? icache_pkt.vaddr[byte_offset_width_lp+:`BSG_MAX(bank_offset_width_lp,1)] : '0;
I also don't think you need the clause here since the signal is unused in direct mapped

2020-11-26 03:57 UTC, sripathi-muralitharan commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +  (`BSG_MAX(2, (2*ways_mp-1)))
Added in a comment to remove future confusions and reverted back to the older version.

2020-11-26 03:58 UTC, sripathi-muralitharan commented
In addition to the suggested comments, I also ended up removing a lot of the earlier changes from the I$ code. I think right now it is at the most minimally changed version.

2020-11-26 18:36 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam data_mem_addr_width_lp = (icache_assoc_p > 1) ? (index_width_lp+bank_offset_width_lp) : index_width_lp;
nice!

2020-11-26 18:44 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
>    if (fill_size_in_bank_lp == 1)
Technically unrelated change, but I think it fits here. Can you change bank_sub_offset_width_lp to $clog2 instead of SAFE_CLOG2 and get rid of this if statement?

2020-11-26 18:45 UTC, dpetrisko requested changes
LGTM other than the last change requested and basejump going back to master once all PRs are merged.  Good work!

2020-11-26 20:10 UTC, sripathi-muralitharan commented on bp_me/src/v/cce/bp_uce.sv
>    if (fill_size_in_bank_lp == 1)
Done.

2020-11-26 20:10 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam data_mem_addr_width_lp = (icache_assoc_p > 1) ? (index_width_lp+bank_offset_width_lp) : index_width_lp;
Thanks!

2020-11-27 21:18 UTC, dpetrisko approved these changes

2020-11-27 21:18 UTC, merged