adding new axi wrappers and converters
black-parrot/black-parrot pull request #684
Opened 2020-11-21 00:30 UTC by tanglingshu

Creating new pull request because I just can't update my obsolete black-parrot top_dev branch correctly

2020-11-21 01:41 UTC, dpetrisko requested changes
Nice, looks pretty good.  We need the wrapper in this PR so that these modules are tested

2020-11-21 01:41 UTC, dpetrisko commented on bp_me/src/v/axi/bp_axi4_to_axi4_lite_converter.v
> +`include "bsg_defines.v"
we want a bp_lite to axi_lite converter, not to convert to axi and then axi-lite.  If we need to convert axi to axi lite, we can typically use existing FPGA IP

2020-11-21 01:41 UTC, dpetrisko commented on bp_me/src/v/axi/bp_axi4_to_axi4_lite_converter.v
> +  , parameter  axi_addr_width_p             = 64 //or 32, has to be either 32 or 64 for axi-lite
assertion?

2020-12-01 02:35 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +          io_resp_cast_o.data[31:0] = 32'hFFFF_FFFF;
what's this write doing?

2020-12-01 02:35 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +        m_axi_lite_wdata_o  = io_cmd_cast_i.data[31:0];
axi_data_width_p?

2020-12-01 02:35 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +        m_axi_lite_wdata_o  = io_cmd_cast_i.data[31:0];
(throughout)

2020-12-01 03:14 UTC, tanglingshu commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +          io_resp_cast_o.data[31:0] = 32'hFFFF_FFFF;
If you're asking about "io_resp_cast_o.data[31:0] = 32'hFFFF_FFFF;", originally I wanted to return all 0s for io_resp's data field on I/O writes, but I looked at the waveform and 32'hFFFF_FFFF was returned as the io_resp data (in blue circle below)
![image](https://user-images.githubusercontent.com/48067062/100692070-e5b89400-333e-11eb-9e88-b262078b932b.png)
If the data field of io_resp on I/O writes should always return 0s, let me know. 

The write strobe is supposed to mask every 8 bits of data (with 1 bit of the strobe). For instance:
data (32bits)= 0xDEADBEEF
write_strb (4bits) = 0x0011
client side should manipulate the data so that it receives 0x0000BEEF. 

I used the io_cmd's header's size field to help me determine what the write strobe should be. So for instance, if the  

msg_size | write_strb
-- | --
1byte | 0x0000_0001
2bytes | 0x0000_0011
4bytes | 0x0000_1111
8bytes | 0x1111_1111


I used shifting bits for now, but I spoke Tommy and he suggested a solution that uses "bsg_decode" and "bsg_expand_bitmask" for that. That's something I'd like to implement later

2020-12-01 03:25 UTC, tanglingshu commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +        m_axi_lite_wdata_o  = io_cmd_cast_i.data[31:0];
Is this referring to what the axi_data_width_p should be? or why does it exist at all? Most of the axi-lite devices use 32bit (at least on genesys 2 board). If BP only supports 64bits for IO communication, then maybe a serdes (PISO/SIPO) is required.

If the above is not what you're asking, may you clarify your original question? Thank you

2020-12-28 23:21 UTC, dpetrisko requested changes

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +          io_cmd_cast_o.header.payload  = bp_out_mem_payload_width_lp'('h0010);
What's this magic number?

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +    assign io_cmd_data_lo[i*8+:8] = (s_axi_lite_wstrb_i[i])
We don't support arbitrary strobes, just aligned accesses. So this doesn't really do much. We should add an assertion that the strobe is correct, though.

Should use bsg_bus_pack to replicate data across the io_cmd.data

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , localparam msg_size_lp                  = `BSG_SAFE_CLOG2(axi_data_width_p/8)
unused

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , input [2:0]                                s_axi_lite_awprot_i
are these enums? If so, declare them?

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , output logic [1:0]                         s_axi_lite_bresp_o
What are the 2 bits for?

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +  wire [2:0] unused_0 = s_axi_lite_awprot_i;
Are these optional ports, or do we only support a single protocol?

If optional, remove. If unsupported, add assertion

2020-12-28 23:21 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +   mem_interface_axi_full_wrapper
nit. These are converters, not wrappers. Adjust comments and rename

mem2axi, io2axil, axil2io

2020-12-28 23:21 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +   	,.reset_i(reset_i)
nit, weird alignment

2020-12-28 23:21 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +   , localparam dword_width_lp         = axi_full_data_width_p
dword is 64 bits, shouldn't be calculated. If only one parameterization is supported, add assertion

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +          io_cmd_cast_o.header.payload             = bp_out_mem_payload_width_lp'('h0010);
magic number?

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , parameter axi_addr_width_p              = 64
Are the restrictions on allowable size here? Should we match to paddr_width_p?

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +  assign io_cmd_w_v = io_cmd_v_i & (io_cmd_cast_i.header.msg_type == e_bedrock_mem_uc_wr);
nit, use ```wire io_cmd_w_v = ``` syntax

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +  always_comb begin
nit, begin / end on their own line

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +  typedef enum logic [1:0] {
don't waste a typedef, just

enum logic [1:0] {} state_n, state_r;

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +       io_resp_cast_o.data[axi_data_width_p-1:0] = (m_axi_lite_rresp_i == '0)
don't need to gate the data, we're not looking at it if it's not valid

2020-12-28 23:21 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +       io_resp_cast_o.data[axi_data_width_p-1:0] = (m_axi_lite_rresp_i == '0)
applies throughout

2020-12-29 00:36 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , parameter axi_addr_width_p              = 64
There is a restriction on the allowable size here. It's either 32 or 64bits. Since the paddr_width_p is 40, I think we can just assign the 40-bit address to the 32/64 bit axi address. AXI32 would be header.addr[31:0] and AXI64 would be header.addr with sign extension I believe.

2020-12-29 00:36 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , localparam msg_size_lp                  = `BSG_SAFE_CLOG2(axi_data_width_p/8)
will remove in the latest commit

2020-12-29 00:43 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +  wire [2:0] unused_0 = s_axi_lite_awprot_i;
The awprot signal exists for axi-lite but it's typically ignored by the client device. The protection encoding is as follows. I think unsupported assertion is more appropriate here 
![image](https://user-images.githubusercontent.com/48067062/103251010-aecca280-492b-11eb-86da-267bf5a1b98b.png)

2020-12-29 00:50 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , output logic [1:0]                         s_axi_lite_bresp_o
The encoding for both bresp and rresp is as follows. I'm defaulting the bresp (write response) to OKAY since I'm not sure if other errors are supported by BP.
![image](https://user-images.githubusercontent.com/48067062/103251235-c7898800-492c-11eb-9ad6-f0738c984cbf.png)

2020-12-29 00:51 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , input [2:0]                                s_axi_lite_awprot_i
yes they are enums but since awprot is unsupported, should I still declare them as enum?

2020-12-29 00:54 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +    assign io_cmd_data_lo[i*8+:8] = (s_axi_lite_wstrb_i[i])
what kind of strobe would be considered a correct strobe?

2020-12-29 00:56 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +          io_cmd_cast_o.header.payload  = bp_out_mem_payload_width_lp'('h0010);
This is the number that I see in the header's payload field in a simulation. I originally set it to 0s but it wasn't passing the test. I do wish to know if there is a significance to it or it is irrelevant in most cases.

2020-12-29 00:57 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +          io_cmd_cast_o.header.payload             = bp_out_mem_payload_width_lp'('h0010);
same as above

2020-12-29 01:03 UTC, tanglingshu commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +  assign io_cmd_w_v = io_cmd_v_i & (io_cmd_cast_i.header.msg_type == e_bedrock_mem_uc_wr);
will correct in the next PR

2020-12-29 01:03 UTC, tanglingshu commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +  typedef enum logic [1:0] {
will correct in the next PR

2020-12-29 01:17 UTC, tanglingshu commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +       io_resp_cast_o.data[axi_data_width_p-1:0] = (m_axi_lite_rresp_i == '0)
this gate is used for valid but erroneous data. In this case, I say that if the client device responded with anything other than "OKAY", then send all 0s to io_resp's data field. I think you're right that most of the time it will be valid and correct data. So if an error response is not of concern, then I can remove this gate.

2020-12-29 07:21 UTC, tanglingshu commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +  always_comb begin
will correct in the next PR

2020-12-29 07:21 UTC, tanglingshu commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +   , localparam dword_width_lp         = axi_full_data_width_p
will remove in the next PR

2020-12-29 07:22 UTC, tanglingshu commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +  bp_unicore
will add multicore option in the next PR. Though multicore doesn't have the same bp_burst interface as unicore. What do I do with that?

2020-12-29 07:22 UTC, tanglingshu commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +   	,.reset_i(reset_i)
will correct in the next PR

2020-12-29 07:22 UTC, tanglingshu commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +   mem_interface_axi_full_wrapper
will correct in the next PR

2021-01-02 08:35 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +  bp_unicore
https://github.com/black-parrot/black-parrot/blob/master/bp_top/test/tb/bp_tethered/wrapper.sv

2021-01-02 08:36 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +  bp_unicore
Rather have them both in this PR, since this file would change name and purpose in another one

2021-01-02 08:37 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +          io_cmd_cast_o.header.payload  = bp_out_mem_payload_width_lp'('h0010);
yes, look into that... The payload is a struct, which fields are being set?

2021-01-02 08:40 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +    assign io_cmd_data_lo[i*8+:8] = (s_axi_lite_wstrb_i[i])
I guess I'm not sure what's legal in the AXI spec. This block looks like it implies any arbitrary set of bytes can be set / unset.

We support contiguous bytes
-----------X
----------XX
-------XXXX
and their shifted variants

bsg_bus_pack is needed for replication

2021-01-02 08:40 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , output logic [1:0]                         s_axi_lite_bresp_o
make an enum

2021-01-02 08:40 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , input [2:0]                                s_axi_lite_awprot_i
yes

2021-01-02 08:42 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +  wire [2:0] unused_0 = s_axi_lite_awprot_i;
just push the assertion on this PR

2021-01-02 08:45 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +   , parameter axi_addr_width_p              = 64
Cool, 64 bits is fine then, add an assertion.

>AXI64 would be header.addr with sign extension I believe.

Sign extension seems weird to me, I would think zero extension is more likely because then you could actually use the entire 64-bit space if you had other peripherals

2021-01-02 08:46 UTC, dpetrisko commented on bp_me/src/v/axi/bp_lite_to_axi_lite_master.sv
> +       io_resp_cast_o.data[axi_data_width_p-1:0] = (m_axi_lite_rresp_i == '0)
we don't support errors on the bus, so there's no difference between a zero and invalid response. Would rather save the hardware. Should loudly fail in simulation if an error comes back though

2021-01-03 04:47 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +          io_cmd_cast_o.header.payload  = bp_out_mem_payload_width_lp'('h0010);
I see, sorry about that. The payload is a memory payload that has:
coherence state: invalid (3'h0)
way_id: 3'h0
lce_id: 4'h2
prefetch: 1'b0
uncached: 1'b0
speculative; 1'b0

I guess this sequence of payload is valid only for the IO coming out of the nbf_loader. Reason why I set this value is that I attached this wrapper to an nbf_loader for simulation. Practically, if any device initiates a transaction with BP, is there a way to figure out the payload field? like a default value?

2021-01-03 04:59 UTC, tanglingshu commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +    assign io_cmd_data_lo[i*8+:8] = (s_axi_lite_wstrb_i[i])
According to the AXI spec, any combination of write strobe is legal. Each bit of the strobe masks 8 bits of the input data. For example:
Input: DEAD_BEEF
wstrb: 0101
Output: 00AD_00EF

I guess we could either do:
1) bsg_bus_pack where we only support limited strobes and make an assertion for unsupported strobes
2) supports arbitrary strobes and write 0s for invalid data

2021-01-13 00:41 UTC, dpetrisko commented on bp_me/src/v/axi/axi_lite_to_bp_lite_client.sv
> +    assign io_cmd_data_lo[i*8+:8] = (s_axi_lite_wstrb_i[i])
>bsg_bus_pack where we only support limited strobes and make an assertion for unsupported strobes

Yeah, that's what I'm suggesting

2021-01-13 00:42 UTC, dpetrisko commented on bp_me/src/v/axi/bp_mem_to_axi_master.sv
> +  function automatic [7:0] len_calc;
@taylor-bsg I know functions are intended to synthesize by spec, but how is tool support?

2021-01-15 19:21 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +    // multi-core + wrapper implementation
In the interest of getting this in, just put an $error here that multicore axi top is not currently supported. I'll make an issue to fix it up in the near future

2021-01-19 16:36 UTC, tanglingshu commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +    // multi-core + wrapper implementation
will make all of the necessary changes throughout this week. Thank you for your patience

2021-01-26 03:31 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_with_axi_wrapper.sv
> +    // multi-core + wrapper implementation
Thanks Ling!

2021-02-16 06:02 UTC, taylor-bsg commented
@tanglingshu Hi Ling! I hope you are well -- how are we doing in terms of finalizing this?

2021-02-24 17:35 UTC, merged