FPGA Signal Alignment Bug
black-parrot/black-parrot pull request #706
Opened 2020-12-14 09:27 UTC by farzamgl

On Vivado, this bug causes the fraction part of the result to be all-zeros when converting between single and double precision floating-point numbers.

2020-12-14 09:35 UTC, dpetrisko requested changes
Weird bug.  Can we get a test reproducing it? And a comment about which Vivado version can't handle the alternate syntax

2020-12-19 01:44 UTC, dpetrisko commented
@taylor-bsg I forget, what was the style guide ruling on this? Explicitly cast width of expressions?

2020-12-19 03:29 UTC, taylor-bsg commented
Yeah, or a concatenation is okay as well — the width is not determined by
the LHS

On Fri, Dec 18, 2020 at 5:44 PM Dan Petrisko <notifications@github.com>
wrote:

> @taylor-bsg <https://github.com/taylor-bsg> I forget, what was the style
> guide ruling on this? Explicitly cast width of expressions?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/black-parrot/black-parrot/pull/706#issuecomment-748400132>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEFG5AAVN4UWG7EJXIXX4C3SVQAQDANCNFSM4U2OFDCQ>
> .
>

2021-01-08 16:09 UTC, dpetrisko approved these changes
Yeah I think we can merge this then, end result was addition to the style guide to use explicit sizing in struct field assignment

2021-01-08 16:34 UTC, merged