WiP: BP Burst interface for ucode and FSM CCEs
black-parrot/black-parrot pull request #707
Opened 2020-12-15 21:38 UTC by muwyse

This PR updates both CCEs to use the BP Burst interface and connect directly to wormhole streamer modules.

This depends on basejump PR 358 (https://github.com/bespoke-silicon-group/basejump_stl/pull/358) and 232 (https://github.com/bespoke-silicon-group/basejump_stl/pull/232)

Single core, ME, multicore, dcache, and icache regressions all pass under VCS.

2020-12-15 21:41 UTC, muwyse commented
I did not make major adjustments to the tiles, so it is possible there is more buffering that can still be removed.

2020-12-16 18:37 UTC, dpetrisko commented on bp_me/src/v/cce/bp_bedrock_size_to_len.sv
> +/**
ah, I see this answers my question on the other PR

2020-12-16 18:39 UTC, dpetrisko commented on bp_me/src/v/cce/bp_cce.sv
> +  // lce request header buffer
Generally better to put the buffers outside the module. In this case, aren't we connecting to wormhole routers which are helpful?

2020-12-16 18:40 UTC, dpetrisko commented on bp_me/src/v/cce/bp_cce_inst_stall.sv
>    // needing to be inout signals for this module when building with VCS.
what's the warning? I've never seen that before

2020-12-16 18:42 UTC, dpetrisko commented on bp_me/src/v/cce/bp_io_cce.sv
Not necessarily part of this PR, but can this be converted to ready_and on both sides? I think so

2020-12-16 18:44 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce.sv
> -    , input                                          lce_req_ready_i
I think this can fairly easily be converted to ready_and since we're stalling in the FSM anyway

2020-12-16 18:48 UTC, dpetrisko reviewed
This is awesome. I haven't looked at the tile stuff yet, I'd believe there's some optimization to be done.

I think at a high level, this should be two PRs.  First, we should do as much ready_and conversion as we can in these modules before converting to burst. That should ensure that we have the fewest required buffers during the next step.  (I'd also be in favor of putting the bugfixes and testing changes in PR 1 just for simplicity)

2020-12-21 19:57 UTC, muwyse commented on bp_me/src/v/cce/bp_bedrock_size_to_len.sv
> +/**
yes, I changed this to be a zero-based length on the output to align with the WH network stuff and the other PR.

2020-12-21 20:01 UTC, muwyse commented on bp_me/src/v/cce/bp_cce.sv
> +  // lce request header buffer
I think I agree in general, not sure about this case. The ucode CCE functionality requires a demanding interface with the inbound message headers. I do think it is nice to have the CCE interface be r&v across the board, though.

I could push these into the cce_wrapper module, but I am not convinced pushing them out beyond that is better. It is nice to be able to take either the ucode or FSM CCE outside the wrapper and use it directly with all r&v interfaces.

2020-12-21 20:03 UTC, muwyse commented on bp_me/src/v/cce/bp_cce_inst_stall.sv
>    // needing to be inout signals for this module when building with VCS.
It (at least used to) comes up with VCS where it thinks these input signals should be in/out instead of just input. I think it has to do with how they get used since the stall_o is basically an OR tree drawn from the input signals. I can try removing and rechecking the compile/warnings/synth checks to see if it still complains.

2020-12-21 20:04 UTC, muwyse commented on bp_me/src/v/cce/bp_io_cce.sv
I'm sure it can, yes, and likely without too much effort.

2020-12-21 20:05 UTC, muwyse commented on bp_me/src/v/lce/bp_lce.sv
> -    , input                                          lce_req_ready_i
Likely, yes. I'll take a look.

2020-12-21 20:08 UTC, muwyse commented
> I think at a high level, this should be two PRs.

This might only be partially possible. It could be doable for things like the LCE, but doing it for CCE might be more effort than it is worth to first change up interfaces then apply burst.

2021-04-21 06:24 UTC, muwyse commented
@dpetrisko I think this is ready for re-review. Single core RISCV tests, multicore tests, ME tests, and check_design.syn CI script all look good. I'll need to do another pass on the changes, but feedback would be great if you can spare a few minutes. Thanks!

2021-04-21 16:13 UTC, muwyse commented on bp_me/src/v/lce/bp_lce.sv
> -    , input                                          lce_req_ready_i
filed issue: https://github.com/black-parrot/black-parrot/issues/846

2021-04-25 22:33 UTC, dpetrisko requested changes
Okay, so this is a doozy.  In general, it looks like there are some unrelated changes in here for ME testbenches, handshakes, etc. If we can merge those in first that would help.

Major thing is we need to start pulling Songchun's stuff in, which I'll try to do over the next week.  The actual burst code I think is reasonable, although we may want to combine with Songchun's stream_pump modules to make burst_pump modules. This would avoid having repetition for interfacing between an FSM and a bp burst interface which we're going to be doing all over the place

2021-04-25 22:33 UTC, dpetrisko commented on bp_me/src/v/cce/bp_cce.sv
> +  logic lce_resp_v, lce_resp_yumi;
Related to above, but if we do need fifos here, they should probably be twofers so that they don't have a bubble?

2021-04-25 22:33 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +            if (((uc_store_v_li || uc_amo_v_li) && (~uc_hit_v_li || (l1_writethrough_p == 1))) || wt_store_v_li)
Undo this change, I believe it's a bug from rebase

2021-04-25 22:33 UTC, dpetrisko commented on bp_top/src/v/bp_tile.sv
> +  // Mem Command
We won't want to merge this part in, will want to incorporate Songchun's stream cache slice

2021-04-25 22:33 UTC, dpetrisko commented on bp_me/src/v/cce/bp_cce_msg.sv
> +  wire [counter_width_lp-1:0] mem_resp_size_in_packets =
I know we try to keep hardcoded enum values to a minimum, but we have these types of expressions everywhere in the code. Can we just enshrine that msg_size == 2**mem_resp.size? That makes the math here (and everywhere into just divides / shifts

2021-04-25 22:33 UTC, dpetrisko commented on bp_top/src/v/bp_tile.sv
> +  // TODO: fix me!
The bug here is that cfg, clint, cache, or loopback are ready->valid rather than ready-valid&?

2021-04-27 22:17 UTC, muwyse commented
> Why does the ucode CCE require demanding? Seems like the data buffering policy would be the same for both, but maybe I'm missing something

Basically, the ucode cce can be stalled by various internal events or conditions. I can look into this more, but as it stands, it is easier to reason about it if it gets to be demanding (valid->yumi) as opposed to helpful (ready&valid).

2021-05-01 01:12 UTC, dpetrisko commented on bp_me/src/v/cce/bp_cce.sv
> +  // lce request header buffer
discussed offline

2021-05-01 01:13 UTC, dpetrisko commented on bp_me/src/v/cce/bp_cce.sv
> +  logic lce_resp_v, lce_resp_yumi;
discussed offline. mem_resp needs to be helpful due to arbitration policies.  Other FIFOs can most likely be removed

2021-05-18 23:19 UTC, muwyse commented on bp_me/src/v/cce/bp_bedrock_size_to_len.sv
> +module bp_bedrock_size_to_len
The intent is this module computes the number of data packets that would be required if data exists for the message. The module that consumes the len_o output from here is responsible for examining the message type (or other handshake info, e.g., has_data signal in BedRock Burst) to determine if data exists or not for the message being processed.

2021-05-18 23:20 UTC, muwyse commented on bp_me/src/v/cce/bp_cce.sv
> +  logic lce_resp_v, lce_resp_yumi;
Not addressing this in the PR. These are only buffering the headers (about 64-bits a piece) so the cost isn't huge.

2021-05-18 23:24 UTC, muwyse commented on bp_me/src/v/cce/bp_cce.sv
> +  logic lce_resp_v, lce_resp_yumi;
opened #869 to track

2021-05-18 23:34 UTC, muwyse commented on bp_me/src/v/cce/bp_cce_msg.sv
> +  wire [counter_width_lp-1:0] mem_resp_size_in_packets =
Yes, I am good with that for the BedRock message size enum. I see no reason why we would want to change the values. I will add a comment to the BedRock package definitions.

2021-05-19 00:04 UTC, muwyse commented on bp_top/src/v/bp_tile.sv
> +  // Mem Command
This will be separate PR. Opened #870 to track

2021-05-25 16:43 UTC, muwyse commented
@dpetrisko this should be ready for review and merge to me_dev

2021-05-26 02:24 UTC, dpetrisko commented
Awesome. It looks great at a glance, but I probably won't have time to do a thorough review until next week.  Have you done any performance measurements?

2021-06-07 23:05 UTC, dpetrisko approved these changes
Sorry for the delay. Minor clarifications and an offline comment.

I think before merging into dev, we should delete the _to_lite / _from_lite modules and replace with burst_to_stream anywhere applicable. But we can merge this to me_dev first, no problem.

I would also like to update songchun's stream cache controller and merge that in before  going to dev.

Overall, awesome!

2021-06-07 23:07 UTC, dpetrisko commented on bp_top/src/v/bp_tile.sv
> +    ,.reset_i(reset_i)
These all need to be reset_r, not reset_i

2021-06-08 16:11 UTC, muwyse commented on bp_me/src/v/cce/bp_cce_inst_decode.sv
> +              decoded_inst_o.src_b.flag = op_type_u.rtype.src_b.flag;
correct. These particular instructions do not appear to be used in the current microcode

2021-06-08 17:06 UTC, muwyse commented on bp_common/src/v/bsg_serial_in_parallel_out_passthrough_dynamic_last.v
> + * This module passes throught he last input data word directly to the output
typo

2021-06-08 17:08 UTC, muwyse commented on bp_common/src/v/bsg_serial_in_parallel_out_passthrough_dynamic_last.v
> +    assign v_o = last_i | last_r | (v_i & data_en_li[max_els_p-1]);
No. The way I implemented it does not require last_i to be raised on the last serial word if the SIPO is being completely filled.

2021-06-08 17:19 UTC, muwyse commented on bp_me/src/v/wormhole/bp_burst_to_wormhole.sv
> +/**
They are very similar, yes. I think it is beneficial to have one specialized for BedRock Burst and another for BedRock Stream protocols. They differ mainly in the input interface. The wormhole streamer takes in pr_data_beats_i to specify the length of the message whereas this uses the has_data and last signals from Burst to determine the number of data beats required.

The question is for a "generic" protocol X <-> wormhole, what are the signals required on the X side. In my opinion, pr_data_beats_i doesn't make sense for Burst or Stream because they already contain the required flow control info with the has_data/last signaling. Adding logic to back-compute pr_data_beats_i seems silly. However, we could decide that the bsg_wormhole_stream_in/out talks to something that is effectively BedRock Burst or Stream. Then, we could wrap the stream_in/out to easily create burst-wormhole and stream-wormhole converters for BP.

2021-06-08 18:29 UTC, muwyse commented
In response to this question in bp_cce_msg.sv:
> I think we can just cast here then without the muxing?

I don't think it can be a direct cast. The message size is in log2(bytes) but we need to convert to dword_width_gp packets. I think the mux could potentially be transformed to some shifts and maybe a subtract by one (or I convert the FSM logic to handle the off by one thing to remove the dynamic subtract).

2021-06-08 20:38 UTC, muwyse commented on bp_me/src/v/cce/bp_cce_msg.sv
> +  wire [counter_width_lp-1:0] mem_resp_size_in_packets =
Okay, I think I have this simplified now. A similar approach could be used in the bp_bedrock_size_to_len module.

2021-06-08 21:15 UTC, muwyse commented
>I think before merging into dev, we should delete the _to_lite / _from_lite modules and replace with burst_to_stream anywhere > applicable. But we can merge this to me_dev first, no problem.
>
> I would also like to update songchun's stream cache controller and merge that in before going to dev.

I think both of these are reasonable. I have already started working to change interfaces on the "uncore" modules in the tile so that everything uses burst or stream

2021-06-09 00:44 UTC, muwyse commented on bp_common/src/v/bsg_serial_in_parallel_out_passthrough_dynamic_last.v
> +    logic last_r;
If it weren't for the passthrough and last behavior I think I would agree. However, since the last serial input is never buffered AND there is no requirement that the SIPO fill up for a transaction (i.e., last can go high with any serial input word), I don't think the logic would be simplified.

2021-06-09 01:13 UTC, merged