[WIP] Minimizing cache tags
black-parrot/black-parrot pull request #755
Opened 2021-02-07 17:28 UTC by dpetrisko

Currently, we store the entire physical tag in the caches. This is wasteful, because the upper bits of address are used for uncacheable memory.

- [X] Add new ctag parameter
- [X] Shrink cache tags to the cacheable memory size
- [ ] Shrink directory stores to cacheable memory size

2021-02-07 18:12 UTC, muwyse requested changes

2021-02-07 18:12 UTC, muwyse commented on bp_me/src/v/lce/bp_lce_cmd.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, ctag_width_p, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
I think the LCE will need more changes than just using ctag_width_p in the macros. It likely does something with the actual address to/from cache commands and LCE req/cmd/resp messages.

2021-02-07 18:53 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce_cmd.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, ctag_width_p, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
The outgoing messages are all the full address - the tag parameter is only used for tag_mem_pkts. Or at least, that’s what is intended :)

2021-02-07 23:52 UTC, taylor-bsg commented on bp_common/src/include/bp_common_addr_pkgdef.svh
> +  // 4 GB
feels like this should be in a machine config struct? all of these other addresses more or less are located on chip and will be self-consistent with the verilog (right?), but feels like people may be surprised to learn that their 64-bit processor can only do 4GB

2021-02-08 01:55 UTC, dpetrisko commented on bp_common/src/include/bp_common_addr_pkgdef.svh
> +  // 4 GB
Yeah that's a good point, will update

2021-02-08 21:07 UTC, dpetrisko commented on bp_me/src/v/lce/bp_lce_cmd.sv
> +   `declare_bp_cache_engine_if_widths(paddr_width_p, ctag_width_p, sets_p, assoc_p, dword_width_gp, block_width_p, fill_width_p, cache)
Looking through the lce_cmd code nothing stands out to me as depending on particular address bits, and I've confirmed in the cache_engine macros tag_width is only used in tag_mem_pkt_s and tag_info_s. Do you see any other problematic cases?

2021-02-10 05:16 UTC, merged