Sub-Bank Masking in the D$
black-parrot/black-parrot pull request #761
Opened 2021-02-15 17:59 UTC by sripathi-muralitharan

Currently, the iterative filling strategy supports fill widths of size equal to the bank width or higher. This PR adds the capability to partially fill banks upto a minimum width of 64-bits in the unicore configuration.

Other fixes: The D$ testbench was outdated with recent changes so there are some fixes for that as well. 

Testing: I added a config and included that config to ci/weird_config.sh script as well.

2021-02-15 22:25 UTC, dpetrisko commented on bp_top/test/common/bp_nonsynth_if_verif.sv
> +  if ((icache_fill_width_p < 64) || (dcache_fill_width_p < 64))
This is a less stringent constraint -- we don't support 65 bit fill, for example

2021-02-15 22:29 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  localparam sub_fill_size_in_bank_lp = bank_width_lp / fill_width_p;
this seems backwards? bank size in fill?

2021-02-15 22:41 UTC, sripathi-muralitharan commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  localparam sub_fill_size_in_bank_lp = bank_width_lp / fill_width_p;
That's right. I take it to mean number of fills required to fill a bank. I can rename it to say `bank_size_in_fill_lp`

2021-02-15 22:43 UTC, sripathi-muralitharan commented on bp_top/test/common/bp_nonsynth_if_verif.sv
> +  if ((icache_fill_width_p < 64) || (dcache_fill_width_p < 64))
Hmm, I can maybe write it as - `BSG_SAFE_CLOG2(*cache_fill_width_p) != 8, 16, 32 or 64`

2021-02-16 04:04 UTC, dpetrisko commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +      logic [`BSG_MAX(1, `BSG_SAFE_CLOG2((block_data_width_mp/fill_width_mp)/ways_mp))-1:0] sub_fill_index; \
I think just fill_index is sufficient? block_data_width/fill_width should give the correct index, even if fill_width < bank size

2021-02-16 04:04 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +  assign bank_index = (fill_size_in_bank_lp != 0)
Yeah I think this will be cleaner just having a single fill_index. The cache itself can slice of the subbank index

2021-02-16 04:06 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  logic [banks_per_block_lp-1:0][`BSG_MAX(fill_size_in_bank_lp, 1)-1:0] data_mem_pkt_fill_mask_expanded;
looks like this didn't get updated, fill_size_in_bank

2021-02-16 04:07 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  logic [banks_per_block_lp-1:0][`BSG_MAX(fill_size_in_bank_lp, 1)-1:0] data_mem_pkt_fill_mask_expanded;
or below

2021-02-16 04:10 UTC, sripathi-muralitharan commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  logic [banks_per_block_lp-1:0][`BSG_MAX(fill_size_in_bank_lp, 1)-1:0] data_mem_pkt_fill_mask_expanded;
No, here I want to use `fill_size_in_bank` (as before) to indicate which bank should be the one I fill to. I generate a separate bank mask below that will get ANDed with this one.

2021-02-16 04:11 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      #(.num_out_p(bank_size_in_fill_lp))
if bsg_decode has width 0, is o== 1'b1? what about width 1?

2021-02-16 04:14 UTC, sripathi-muralitharan commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      #(.num_out_p(bank_size_in_fill_lp))
For width 1, o = 1'b1. There doesn't seem to be zero width support for it now. If num_out_p was 0, it would actually create a 2-bit output because of the range becoming [-1:0]

2021-02-16 04:38 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  logic [banks_per_block_lp-1:0][`BSG_MAX(fill_size_in_bank_lp, 1)-1:0] data_mem_pkt_fill_mask_expanded;
oh I didn't know both variables existed

2021-02-16 04:40 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      #(.num_out_p(bank_size_in_fill_lp))
so if we make fill_size_in_bank and bank_size_in_fill minimum 1 I think both these special cases go away? Does that cause problems elsewhere?

2021-02-16 05:06 UTC, sripathi-muralitharan commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +      logic [`BSG_MAX(1, `BSG_SAFE_CLOG2((block_data_width_mp/fill_width_mp)/ways_mp))-1:0] sub_fill_index; \
Block width / fill width gives the number of fills required to fill that block. Earlier when we had fill widths >= bank widths this could sufficiently address the case of filling a single bank or multiple banks. Now we want to have a way to address locations within a bank as well where the sub fill index helps. 

fill index --> which bank
sub fill index --> location within bank

Maybe combine both into a 2-D array like [bank _index - 1: 0][within_bank_index-1:0] although assignment might become slightly complicated (I think)

2021-02-16 05:08 UTC, sripathi-muralitharan commented on bp_me/src/v/cce/bp_uce.sv
> +  assign bank_index = (fill_size_in_bank_lp != 0)
Same reasoning as above. I don't think we can have just one variable tracking both the physical bank and the logical bank. 

Example: 
512-bit block, 128-bit bank, 64-bit fills. 4 physical banks, 8 logical banks.

2021-02-16 05:11 UTC, sripathi-muralitharan commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      #(.num_out_p(bank_size_in_fill_lp))
There shouldn't be any problems. A case where both become 1 is when we have 512-bit blocks and 64-bit fills with 64-bit banks. In that case, the conditional statement defaults to what we had before.

2021-02-16 05:12 UTC, dpetrisko commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +      logic [`BSG_MAX(1, `BSG_SAFE_CLOG2((block_data_width_mp/fill_width_mp)/ways_mp))-1:0] sub_fill_index; \
block_width = 512
fill_width = 64
direct mapped.


fill_index ranges from 0-7 but we have only 1 bank...

2021-02-16 05:12 UTC, sripathi-muralitharan commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      #(.num_out_p(bank_size_in_fill_lp))
The minimums for both of them is actually 0 since clog2(0) is 0. Even BSG_SAFE_CLOG2(0) is 0. Don't know if we want to be safe wrt zero as well but I think it should be reasonable.

2021-02-16 05:12 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +  assign bank_index = (fill_size_in_bank_lp != 0)
physical bank is just a bit slice of logical bank

2021-02-16 05:17 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +  assign bank_index = (fill_size_in_bank_lp != 0)
which is what I'm calling fill_index :)

2021-02-16 15:08 UTC, taylor-bsg reviewed
May I suggest that you pull out the partial SRAM use into a cleanly abstracted module in BaseJump STL? I think that thinking about that interface will make the logic cleaner here, and also result in a reusable module. 

See for example, this module, https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_mem/bsg_mem_1rw_sync_mask_write_bit_banked.v, which does the opposite. :-)

2021-02-16 15:30 UTC, dpetrisko commented
That’s a great idea! Would solve the byte vs non-byte masked parameterization in the icache, as well

2021-02-16 16:31 UTC, sripathi-muralitharan commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +      logic [`BSG_MAX(1, `BSG_SAFE_CLOG2((block_data_width_mp/fill_width_mp)/ways_mp))-1:0] sub_fill_index; \
When assoc_p is 1, fill index is set to 0. So no, it won't. Whereas sub_fill_index will do what you just said.

2021-02-16 16:33 UTC, sripathi-muralitharan commented on bp_me/src/v/cce/bp_uce.sv
> +  assign bank_index = (fill_size_in_bank_lp != 0)
Isn't it the other way around. For the sub-bank fill case, we have smaller but more logical banks. So logical banks become bit slices of physical banks right?

2021-02-16 18:51 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +  assign bank_index = (fill_size_in_bank_lp != 0)
What I mean is that having more logical banks means the logical bank index is larger. The physical bank index is a bit slice within the logical bank address space

2021-02-16 18:51 UTC, dpetrisko commented on bp_common/src/include/bp_common_cache_engine_if.svh
> +      logic [`BSG_MAX(1, `BSG_SAFE_CLOG2((block_data_width_mp/fill_width_mp)/ways_mp))-1:0] sub_fill_index; \
discussed offline

2021-02-16 18:53 UTC, dpetrisko commented on bp_common/src/include/bp_common_cache_engine_if.svh
>        logic [(block_data_width_mp/fill_width_mp)-1:0] fill_index;                             \
I think this should be `BSG_SAFE_CLOG2(block_data_width_mp/fill_width_mp)-1:0], incidentally

2021-02-16 18:53 UTC, dpetrisko commented
Made an issue for the subbanked ram: https://github.com/bespoke-silicon-group/basejump_stl/issues/400

2021-02-25 01:48 UTC, dpetrisko commented
fixes #736

2021-03-27 00:29 UTC, sripathi-muralitharan commented on bp_me/src/v/cce/bp_uce.sv
> +  assign bank_index = (fill_size_in_bank_lp != 0)
Have a look at what's there now. I think its cleaner.

2021-03-27 00:30 UTC, sripathi-muralitharan commented on bp_common/src/include/bp_common_cache_engine_if.svh
>        logic [(block_data_width_mp/fill_width_mp)-1:0] fill_index;                             \
Yup, refactored to do this.

2021-03-27 04:58 UTC, dpetrisko requested changes

2021-03-27 04:58 UTC, dpetrisko commented on bp_common/src/include/bp_common_aviary_pkgdef.svh
> +  localparam bp_proc_param_s bp_unicore_l1_sub_bank_mask_override_p =
nit;

bp_unicore_l1_subbank_override_p

2021-03-27 04:58 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  logic [(2**bank_fill_index_width_lp)-1:0][`BSG_MAX(fill_size_in_bank_lp, 1)-1:0] data_mem_pkt_fill_mask_expanded;
logic [assoc_p-1:0]?

2021-03-27 04:58 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +    ,.expand_p(`BSG_MAX(1, fill_size_in_bank_lp))
Probably should modify bsg_expand_bitmask so that .expand_p(0) also acts as passthrough (like 1)

2021-03-27 04:58 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  assign bank_fill_index  = (assoc_p > 1) ? data_mem_pkt_cast_i.fill_index[lg_num_subbanks_lp+:`BSG_MAX(bank_fill_index_width_lp, 1)] : '0;
bsg_decode .num_out_p(1) should always be 1, so no need to make zero explictly

2021-03-27 04:58 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  // Using BSG_MAX gets rid of illegal part select errors
Same comments as I$ apply

2021-03-27 04:58 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam lg_num_subbanks_lp       = `BSG_SAFE_CLOG2(num_subbanks_lp);
I don't think BSG_SAFE_CLOG2(0) does what you think... $clog2(0)

2021-03-27 04:58 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam bank_fill_index_width_lp = $clog2(block_size_in_fill_lp) - lg_num_subbanks_lp;
`BSG_SAFE_CLOG2(block_width_p/fill_width_p)?

2021-03-27 04:58 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam bank_fill_index_width_lp = $clog2(block_size_in_fill_lp) - lg_num_subbanks_lp;
or $clog2, as needed

2021-03-27 16:04 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam lg_num_subbanks_lp       = `BSG_SAFE_CLOG2(num_subbanks_lp);
Yeah, I want it to return 0 when num_subbanks_lp is 0.

2021-03-27 16:05 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.sv
> +  logic [(2**bank_fill_index_width_lp)-1:0][`BSG_MAX(fill_size_in_bank_lp, 1)-1:0] data_mem_pkt_fill_mask_expanded;
Yeah makes sense. Will get that in, in the next commit.

2021-03-27 16:05 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.sv
> +    ,.expand_p(`BSG_MAX(1, fill_size_in_bank_lp))
Alright, will open a PR in basejump for that.

2021-03-27 16:13 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.sv
> +  assign bank_fill_index  = (assoc_p > 1) ? data_mem_pkt_cast_i.fill_index[lg_num_subbanks_lp+:`BSG_MAX(bank_fill_index_width_lp, 1)] : '0;
Gotcha. My intention was actually to get rid of a build warning that says "Index out of bounds". But even with the change I have now, it doesn't go away. I need the expression to be the way it is to be general. This comes up when the cache is direct-mapped with 512 bit banks and 64 bit fills.

2021-03-27 16:14 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam bank_fill_index_width_lp = $clog2(block_size_in_fill_lp) - lg_num_subbanks_lp;
But the argument to $clog2() as given is block_size_in_fill_lp which is exactly that. Is your intention to go for more clarity?

2021-03-27 16:17 UTC, sripathi-muralitharan commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  // Using BSG_MAX gets rid of illegal part select errors
Should I get rid of the BSG_MAX comment? Is it obvious why that macro was used?

2021-03-27 17:09 UTC, sripathi-muralitharan commented on bp_fe/src/v/bp_fe_icache.sv
> +    ,.expand_p(`BSG_MAX(1, fill_size_in_bank_lp))
https://github.com/bespoke-silicon-group/basejump_stl/pull/423

2021-04-12 02:08 UTC, dpetrisko commented on bp_fe/src/v/bp_fe_icache.sv
> +  localparam bank_fill_index_width_lp = $clog2(block_size_in_fill_lp) - lg_num_subbanks_lp;
yeah

2021-04-19 21:24 UTC, dpetrisko commented
Just noting to myself, this PR needs to solve the critical word snooping problem (32-bit fill), resume on 64 rather than during the first word

2023-07-18 06:24 UTC, dpetrisko commented
Closing for staleness; someone else could pick this up some day

2023-07-18 06:24 UTC, closed without merging