Self invalidation in D$ and uncached mode support
black-parrot/black-parrot pull request #767
Opened 2021-02-20 04:44 UTC by Shashank-Vijay

This PR contains the following:
- Self invalidation in D$ in case of a hit during uncached mode
- UCE changes to support the above
- Removal of uncached mode fault in mmu

2021-02-20 05:54 UTC, dpetrisko commented
Corresponding PR in bp_tests?

2021-02-20 06:27 UTC, dpetrisko requested changes
Nice! Many minor changes, but major change is to do the self-invalidation in TV, not TL. Reason being that doing in TL requires exposing a path from flush to the RAMs, but also exposes a security hole where a speculative invalidation could occur

2021-02-20 06:27 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  assign tag_mem_self_invalidate = uncached_op_tl & |tag_match;
Should use signals from TV to avoid critical path and spurious flushes (need to flush TL+TV)

2021-02-20 06:27 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +    for (integer i = 0; i < assoc_p; i++) begin
nit: use same 
  begin
  end
style

2021-02-20 06:27 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      ? paddr_tl[block_offset_width_lp+:sindex_width_lp]
TV

2021-02-20 06:27 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire stat_mem_fast_read = ~flush_i & ((v_tv_r & ~early_v_o) | (v_tv_r & uncached_op_tv_r));
only need to read on hit + uncached_op

2021-02-20 06:27 UTC, dpetrisko commented on bp_common/src/v/bp_pma.sv
> +   , input                        uncached_i
-> uncached_mode_i

2021-02-20 06:27 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +    for (integer i = 0; i < assoc_p; i++) begin
(throughout)

2021-02-20 06:27 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +            if (cache_req_metadata_cast_i.dirty)
need to wait until data is valid (cache_req_metadata_v_r)

2021-02-20 06:27 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +        e_check_dirty:
-> e_uc_writeback_evict

2021-02-20 06:27 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +            if (cache_req_metadata_cast_i.dirty)
(both state_transition and this if statement)

2021-02-20 06:27 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +        e_data_writeback:
-> e_uc_writeback_write_req

2021-02-20 06:27 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
>    wire miss_load_v_li  = cache_req_v_r & cache_req_r.msg_type inside {e_miss_load};
miss_load_v_r, miss_store_v_r, miss_v_r to be consistent

2021-02-20 20:09 UTC, Shashank-Vijay commented
> Corresponding PR in bp_tests?

Yeah, I'll open that after some clean up and commenting.

2021-02-20 20:10 UTC, Shashank-Vijay commented on bp_me/src/v/cce/bp_uce.sv
> +            if (cache_req_metadata_cast_i.dirty)
Which state transition are you referring to?

2021-02-21 00:35 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +            if (cache_req_metadata_cast_i.dirty)
cache_req_metadata_cast_i is not necessarily valid here. We need to use cache_req_metadata_r and gate it with cache_req_metadata_v_r. if you just do & cache_req_metadata_v_r, then we'll fall through to the else statement here and move to send_critical if the metadata isn't present

2021-02-21 01:15 UTC, dpetrisko requested changes
No major issues, mostly maintainability! Need that bp_tests PR though to verify before and after.  Have you run regression on the writethrough configuration with these changes?

2021-02-21 01:15 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  logic tag_mem_self_invalidate, flush_self;
Declare these signals with the other globals, not here in TL
logic sram_hazard_flush, miss_request_flush;

wire flush_self = flush_i | sram_hazard_flush | miss_request_flush;

Use a wire for tag_mem_fast_read below, don't declare here

2021-02-21 01:15 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  logic tag_mem_self_invalidate, flush_self;
assign sram_hazard_flush = tag_mem_fast_write;
assign miss_request_flush = cache_req_yumi_i & ~uncached_store_req & ~wt_req

2021-02-21 01:15 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +        if (tag_mem_self_invalidate)
A little better for x-pessisim would be

```
case ({tag_mem_fast_write, tag_mem_pkt_cast_i.opcode})
  {1'b1, 3'???}:
    begin
       // self invalidation stuff
    end
  {1'b0, e_cache_tag_mem_set_tag}: 
    begin
       // etc.
```

2021-02-21 03:05 UTC, Shashank-Vijay commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      ? paddr_tv_r[block_offset_width_lp+:sindex_width_lp]
This is defined within an if statement. Should I pull that out?

2021-02-21 08:25 UTC, Shashank-Vijay commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire cache_req_metadata_v = (cache_req_yumi_i & ~wt_req & ~fencei_req);
This causes a problem in the writethrough config. If there is a load request immediately following the wt request, the cache_req_metadata sent for the wt_req will be active when the load reaches the send_critical state. The dirty bit at this point is X, so the state resolves to an X which eventually leads to a stall (observed while running rv64ui-p-sd with the writethrough config).

2021-02-21 08:27 UTC, Shashank-Vijay commented
> No major issues, mostly maintainability! Need that bp_tests PR though to verify before and after. 
I have opened the PR in bp_tests. 
> Have you run regression on the writethrough configuration with these changes?
Yeah, the riscv and beebs regressions pass for the writethrough config. Only one change suggested above was causing a stall in the store tests of the riscv suite, I've mentioned in one of the comments.

2021-02-22 01:52 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire cache_req_metadata_v = (cache_req_yumi_i & ~wt_req & ~fencei_req);
That would happen for uc store then

2021-02-22 01:52 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire cache_req_metadata_v = (cache_req_yumi_i & ~wt_req & ~fencei_req);
uc_store
load

2021-02-22 01:53 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +      ? paddr_tv_r[block_offset_width_lp+:sindex_width_lp]
oh, paddr_index_tv and paddr_tag_tv should be assigned in TV

2021-02-22 01:54 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire cache_req_metadata_v = (cache_req_yumi_i & ~wt_req & ~fencei_req);
Should add a test for this case as well

2021-02-22 02:01 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire cache_req_metadata_v = (cache_req_yumi_i & ~wt_req & ~fencei_req);
thinking about an actual fix though

2021-02-22 02:35 UTC, Shashank-Vijay commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire cache_req_metadata_v = (cache_req_yumi_i & ~wt_req & ~fencei_req);
Can we use a dff_bypass so that the metadata coming through in that cycle is the one that is used instead of the one in metadata_r, and the metadata_r is used otherwise?

2021-02-22 03:03 UTC, dpetrisko commented on bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
> +  wire cache_req_metadata_v = (cache_req_yumi_i & ~wt_req & ~fencei_req);
doesn't fix the fundamental interface issue. The only timing requirement right now is that the cache_req_metadata must come at the same cycle or any cycle after the cache_req, which seems incompatible with the capability of sending back to back requests, but we'll need to draw up a table and compare timing diagrams to rely prove correctness

2021-02-23 07:55 UTC, dpetrisko commented on docs/interface_specification.md
> +Additionally, the Cache Engine may require some metadata in order to service cache misses. This metadata may not be available at the same time as the request, due to the nature of high performance ca
Keep old sentence the same. Add "The latency between a cache request and its metadata must be a known constant for all message types, under all backpressure conditions.

2021-02-23 07:58 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +                              : uc_hit_v_li
I think (uc_hit_v_li & (l1_writethrough_p == 0)), else we'll writeback in our writethrough cache

2021-02-23 08:00 UTC, dpetrisko commented on bp_me/src/v/cce/bp_uce.sv
> +                              : uc_hit_v_li
Can you also add an assertion:

assert ((l1_writethrough_p == 0) || !(state_r inside {e_uc_writeback_evict, e_writeback_evict ......

2021-02-23 08:04 UTC, dpetrisko requested changes
Few very minor changes requested, plus the test we discussed offline.  Then LGTM! Great job!

2021-02-23 12:42 UTC, dpetrisko commented
We do have to reconcile the amosub differences with @muwyse WRT the amo_subops

2021-02-25 01:44 UTC, dpetrisko approved these changes
Great work!

2021-02-25 01:45 UTC, merged