Remove Buffering in lite to burst modules
black-parrot/black-parrot pull request #769
Opened 2021-02-23 07:23 UTC by Songchun-Li

This PR is aimed at fixing issue #729.

In current design of lite to burst conversion modules, header and data buffers account for a majority of area consumption. Also, a bubble is introduced between consecutive no-data request, which is inefficient.

This PR replaces the header fifo with bypass registers, and make use of the sipo/piso_passthrough_dynamic to hold the data. These changes not only reduce the area consumption of the conversion modules, but also pass through the header and data from the input to output at the same cycle.

This change passes weird configure regression.

2021-02-23 11:24 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_burst.sv
> +    header_v_loeg
header_v_reg

(search and replace? :))

2021-02-23 11:28 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_burst.sv
> +  logic data_bursting_r, data_burst_clear, data_ready_and_lo;
So you wouldn't have to hold the data here as long as the input module here is also a ready_and_valid. May require upstream changes to convert from ready-then-valid to ready-valid-and, but I think it's worth it

2021-02-23 11:29 UTC, dpetrisko requested changes
burst to lite looks great. lite to burst can remove the data regs, with some care

2021-02-26 00:22 UTC, Songchun-Li commented on bp_me/src/v/wormhole/bp_lite_to_burst.sv
> +  logic data_bursting_r, data_burst_clear, data_ready_and_lo;
I went through the modules using the lite to burst module, the main barrier is in bp_unicore_no_l2, where lite2burst is connected to the cmd arbiter, a ready_then_valid handshake. But the good thing is lite2burst will be replaced with stream2burst later with the stream_pump attached to the UCE side. 

Therefore, my idea is adding a temporary fifo between the arbiter and the lite2burst to keep it working, before the stream2burst replaces it?

2021-02-26 00:33 UTC, dpetrisko commented on bp_me/src/v/wormhole/bp_lite_to_burst.sv
> +  logic data_bursting_r, data_burst_clear, data_ready_and_lo;
Yeah I think that's a good solution

2021-02-27 03:48 UTC, Songchun-Li commented
The header and data reg in lite_to_burst are removed, and the handshake connection of the conversion modules are checked.

2021-02-27 22:29 UTC, dpetrisko approved these changes

2021-02-27 22:29 UTC, merged