[WiP]: Fix handshake signal names and identify mismatches
black-parrot/black-parrot pull request #838
Opened 2021-04-14 23:22 UTC by muwyse

The BP repo is littered with ambiguous signal names (i.e., ready_i, is it ready_and or ready_then?). This change aims to clarify and fix a subset of these signal naming issues as they keep cropping up when implementing new features.

2021-04-14 23:41 UTC, dpetrisko commented
This is great, thanks for starting this.  Just to paraphrase https://docs.google.com/document/d/1xA5XUzBtz_D6aSyIBQUwFk_kSUdckrfxa2uzGjMgmCU/edit#

(All other combinations are legal)
Consumers:
```
// Deprecated, should be replaced with ready_and_o and & internally
,.v_i(ready_and_li & v_lo)
,.ready_then_o(ready_and_li)

,.v_i(v_lo)
,.yumi_o(ready_and_li // ILLEGAL, USE A FIFO)
```

Producers:
```
,.v_o(v_li)
,.ready_then_i(then_ready_li // ILLEGAL, USE A FIFO)

// Deprecated, should be replaced with ready_and_i and & internally
,.v_o(v_li)
,.yumi_i(ready_and_lo & v_li)
```

I scribbled this out so it's possible there are typos, but we should settle the taxonomy

2021-04-15 03:12 UTC, muwyse commented
I think the BSG coding guidelines doc clarifies most of what we need, except for a couple small "typo" items that could be fixed (table on bottom of pg4 should have rv& renamed to r&v and v->r renamed to v->y or v->yumi for consistency with text).

I think the only thing we may want to clarify is if a signal's direction should be given relative to producer or consumer. For example, if we have the following:
`// producer
.v_o()
.ready_and_i()

// consumer
.v_i()
.ready_and_o()`

is the valid signal connecting these named `v_lo` or `v_li`? In other words, is directionality naming relative to producer or consumer?

2021-04-15 03:14 UTC, muwyse commented
Additionally, and the coding guidelines state this, `then_ready` should never be used because it is ambiguous with `ready_then`

2021-04-15 06:24 UTC, dpetrisko commented
>Additionally, and the coding guidelines state this, then_ready should never be used because it is ambiguous with ready_then

Ah, that's new. Edited the list

>I think the only thing we may want to clarify is if a signal's direction should be given relative to producer or consumer. For example, if we have the following:

I don't think there's a hard and fast rule here. I tend to align the signals to whatever the "driver" of the system is. For instance, if there's a mem_cmd_o, mem_resp_i interface, I would do mem_cmd_lo, mem_resp_li.

>I think the BSG coding guidelines doc clarifies most of what we need,

Yeah the main thing I wanted to highlight is that
1) In BP, we're fine with absorbing the & gate inside the module because we prioritize clarity over gate-level optimization
2) In general, it's legal to connect a ready_and consumer to a ready_then producer, but not vice-versa

2021-04-15 17:18 UTC, taylor-bsg commented
On Wed, Apr 14, 2021 at 11:24 PM Dan Petrisko ***@***.***>
wrote:

> Additionally, and the coding guidelines state this, then_ready should
> never be used because it is ambiguous with ready_then
>
> Ah, that's new. Edited the list
>
> I think the only thing we may want to clarify is if a signal's direction
> should be given relative to producer or consumer. For example, if we have
> the following:
>
> I don't think there's a hard and fast rule here. I tend to align the
> signals to whatever the "driver" of the system is. For instance, if there's
> a mem_cmd_o, mem_resp_i interface, I would do mem_cmd_lo, mem_resp_li.
>
> I think the BSG coding guidelines doc clarifies most of what we need,
>
> Yeah the main thing I wanted to highlight is that
>
>    1. In BP, we're fine with absorbing the & gate inside the module
>    because we prioritize clarity over gate-level optimization
>    2. In general, it's legal to connect a ready_and consumer to a
>    ready_then producer, but not vice-versa
>
>
Not sure what you mean by absorbing the and gate?

I may have not full swapped this in, but within a module you can connect a
ready_and interface of a submodule to another submodule with an interface
of any other kind, including ready_then and yumi, since ready_and is
helpful both as producer and consumer, as long as this is not a "top-level
module" that is connecting two far-apart blocks in the ASIC and would
require ready_and for both producer and consumer.  The rules are more
strict for a module that has multiple separate ready/valid interfaces,
where you have to obey early and lateness rules, per the BaseJump doc.



>    1.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/black-parrot/black-parrot/pull/838#issuecomment-820150055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEFG5AFNOZO6TA66IX5A4ILTI2BBDANCNFSM426KORYA>
> .
>

2021-04-15 18:02 UTC, dpetrisko commented
> may have not full swapped this in, but within a module you can connect a
ready_and interface of a submodule to another submodule with an interface
of any other kind

Not quite true. It's an analogous situation to yumi.

```
// This will be incorrect if v_lo = 1'b1 and ready_then_li = 1'b0
producer p (.v_o(v_lo) ,.ready_and_i(ready_and_li))
consumer c (.v_i(v_lo) ,.ready_then_o(ready_then_li))

// This is the correct connection
producer p (.v_o(v_lo) ,.ready_and_i(ready_then_li))
consumer c (.v_i(ready_then_li & v_lo) ,.ready_then_o(ready_then_li))
```

2021-04-15 18:21 UTC, taylor-bsg commented
Oh I see, you mean, directly connect without gates

On Thu, Apr 15, 2021 at 11:02 AM Dan Petrisko ***@***.***>
wrote:

> may have not full swapped this in, but within a module you can connect a
> ready_and interface of a submodule to another submodule with an interface
> of any other kind
>
> Not quite true. It's an analogous situation to yumi.
>
> // This will be incorrect if v_lo = 1'b1 and ready_then_li = 1'b0
> producer p (.v_o(v_lo) ,.ready_and_i(ready_and_li))
> consumer c (.v_i(v_lo) ,.ready_then_o(ready_then_li))
>
> // This is the correct connection
> producer p (.v_o(v_lo) ,.ready_and_i(ready_then_li))
> consumer c (.v_i(ready_then_li & v_lo) ,.ready_then_o(ready_then_li))
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/black-parrot/black-parrot/pull/838#issuecomment-820624965>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEFG5AAPXEZMYNE4H3XNLC3TI4S2TANCNFSM426KORYA>
> .
>

2021-04-15 18:31 UTC, dpetrisko commented
>Oh I see, you mean, directly connect without gates

Yep! Source: bugs that @muwyse has discovered :)

2021-04-15 23:14 UTC, muwyse commented
add to CI needs to be removed prior to merge

2021-04-15 23:29 UTC, dpetrisko commented on bp_be/test/tb/bp_be_dcache/wrapper.sv
> +              // TODO: mismatch, but okay - connects to ready_and_rev on link
These are fine, can remove comments

2021-04-15 23:49 UTC, dpetrisko requested changes
LGTM! Some clarifications and TODO squashing. Might want to submit a doc PR to bsg_one_fifo but won't block this on it

2021-04-15 23:49 UTC, dpetrisko commented on bp_fe/test/tb/bp_fe_icache/testbench.sv
> +    ,.mem_cmd_v_i(mem_cmd_ready_and_lo & mem_cmd_v_lo)
unnecessary for ready_and

2021-04-15 23:49 UTC, dpetrisko commented on bp_fe/test/tb/bp_fe_icache/testbench.sv
> +     ,.mem_cmd_v_i(mem_cmd_ready_and_lo & mem_cmd_v_lo)
unnecessary

2021-04-15 23:49 UTC, dpetrisko commented on bp_top/src/v/bp_cacc_tile.sv
> +     ,.lce_cmd_ready_then_i(cce_lce_cmd_ready_li)
signal rename here?

2021-04-15 23:49 UTC, dpetrisko commented on bp_top/src/v/bp_io_tile.sv
> +     ,.io_resp_ready_then_i(lce_io_resp_ready_li)
signal rename? I think the handshake is fine though

2021-04-15 23:49 UTC, dpetrisko commented on bp_top/src/v/bp_loopback.sv
>    bsg_one_fifo
We should clarify this in bsg_one_fifo, I don't think it belongs here though. All bsg_fifos are ready_and by default (even if the signal name is wrong)

2021-04-15 23:49 UTC, dpetrisko commented on bp_top/src/v/bp_sacc_tile.sv
> +     ,.lce_cmd_ready_then_i(cce_lce_cmd_ready_li)
same as I/O tile -- rename, verify handshake

2021-04-15 23:49 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_lite.sv
> +  // TODO: handshake violation! CFG is R&V
R&V consumer is fine to connect to R->V producer

2021-04-16 00:00 UTC, muwyse commented on .gitlab-ci.yml
> +    - dev_fix_handshakes
removed

2021-04-16 00:01 UTC, muwyse commented on bp_be/test/tb/bp_be_dcache/wrapper.sv
> +              // TODO: mismatch, but okay - connects to ready_and_rev on link
removed comments on ready_and_o (consumer) feeding ready_then_i (producer)

2021-04-16 00:03 UTC, muwyse commented on bp_top/src/v/bp_unicore_lite.sv
> +  // TODO: handshake violation! CFG is R&V
removed comments

2021-04-16 00:05 UTC, muwyse commented on bp_fe/test/tb/bp_fe_icache/testbench.sv
> +    ,.mem_cmd_v_i(mem_cmd_ready_and_lo & mem_cmd_v_lo)
yep, good catch

2021-04-16 00:05 UTC, muwyse commented on bp_top/src/v/bp_cacc_tile.sv
> +     ,.lce_cmd_ready_then_i(cce_lce_cmd_ready_li)
yep, thanks

2021-04-16 00:11 UTC, muwyse commented on bp_fe/test/tb/bp_fe_icache/testbench.sv
> +     ,.mem_cmd_v_i(mem_cmd_ready_and_lo & mem_cmd_v_lo)
fixed

2021-04-16 00:15 UTC, muwyse commented on bp_top/src/v/bp_io_tile.sv
> +     ,.io_resp_ready_then_i(lce_io_resp_ready_li)
fixed

2021-04-16 00:22 UTC, muwyse commented on bp_top/src/v/bp_loopback.sv
>    bsg_one_fifo
removed comment.

2021-04-16 00:22 UTC, muwyse commented on bp_top/src/v/bp_sacc_tile.sv
> +     ,.lce_cmd_ready_then_i(cce_lce_cmd_ready_li)
renamed

2021-04-16 22:36 UTC, dpetrisko approved these changes
LGTM!

2021-04-16 22:58 UTC, merged