Breaking critical uncached path
black-parrot/black-parrot pull request #888
Opened 2021-06-06 10:15 UTC by dpetrisko

This PR does a few things.

- The most important is the critical path fix in the UCE and LCE.  Currently, we stream out non-blocking requests (uc, wt, l2 amo) in a single cycle. This leads to a path from the cache AMO unit through the cache engine to routers, accelerators, etc.  Instead, this PR delays the output of the request by a single cycle and accepts a new request if the non-blocking request is sent out in the same cycle. In this way, we maintain 100% throughput for non-blocking requests, so there are no cycle-level performance implications.
- The second is adding a tag mem read register in the LCE. This is currently unused because the shadow tags are not needed by the CCE which maintains the true tags. However, I tested it and synthesis rips this unused register out anyway, so I think it's good to have just for future proofing.
- The third is a helper module bsg_dff_sync_read, which maintains a synchronous read buffer. This is purely aesthetic, but there are a bunch of other places in the code where this pattern is used, so we can replace at our leisure.

@muwyse I'm going to pull this into the tapeout branch, so I'd appreciate a quick review. Fine with merging to me_dev after the burst changes if you foresee any conflicts.

2021-06-07 18:04 UTC, muwyse requested changes
LCE/UCE changes look good.

Might be an extra file added that isn't part of PR?

I would like to merge this to me_dev after CCE burst because those changes have been outstanding for so long. I don't see any conflicts between the two changes.

2021-06-07 18:04 UTC, muwyse commented on bp_top/src/v/bp_unicore_complex.sv
> +         ,.link_o(
This looks incomplete?

2021-06-07 18:04 UTC, muwyse commented on bp_top/src/v/bp_unicore_complex.sv
> +         ,.link_o(
Or perhaps this new file isn't actually part of this PR?

2021-06-07 18:54 UTC, dpetrisko commented on bp_top/src/v/bp_unicore_complex.sv
> +         ,.link_o(
Whoops! Yes I'll remove this

2021-06-09 05:28 UTC, dpetrisko commented
good to go?

2021-06-09 15:36 UTC, muwyse approved these changes
LGTM

2021-06-09 15:36 UTC, merged