Adding bedrock register and stream peripherals
black-parrot/black-parrot pull request #890
Opened 2021-06-09 12:31 UTC by dpetrisko

- Converts the tile peripherals to single-beat stream in prep for future
- Adds bp_me_bedrock_register which acts as a Bedrock->GPIO converter. This makes things a little bit easier to connect low-performance peripherals to a tile. Can be expanded as needed for bursting requirements

Depends on #888

2021-06-09 15:58 UTC, muwyse requested changes
Looks good overall. A few small questions to clarify.

2021-06-09 15:58 UTC, muwyse commented on bp_me/src/v/cache/bp_me_bedrock_register.sv
> +   , input                                          mem_resp_ready_and_i
These should conform to BedRock Stream interface (https://github.com/black-parrot/black-parrot/blob/me_dev/docs/bedrock_guide.md#bedrock-stream) - i.e., they are missing the last signal. Or, if they will always be a single data beat then rename and add comment on interface ports saying they are BedRock Lite. If we want to support multi-beat messages in the future (or imply it could happen) we should make this BedRock Stream, add the last signal, and just tie it to 1 for now.

2021-06-09 15:58 UTC, muwyse commented on bp_top/src/v/bp_cfg.sv
> +   , output logic                                   mem_cmd_ready_and_o
Same comment about interface as above.

2021-06-09 15:58 UTC, muwyse commented on bp_top/src/v/bp_clint_slice.sv
> +   , input [xce_mem_msg_header_width_lp-1:0]            mem_cmd_header_i
Same comment about interface as above.

2021-06-09 15:58 UTC, muwyse commented on bp_top/src/v/bp_loopback.sv
> +    , input [cce_mem_msg_header_width_lp-1:0]        mem_cmd_header_i
Same comment about interface as above.

2021-06-09 15:58 UTC, muwyse commented on bp_top/src/v/bp_cfg.sv
> +  assign cce_ucode_addr_o = addr_lo[3+:cce_pc_width_p];
the 3 maybe shouldn't be a magic number, for clarity. Can it be derived from somewhere?

2021-06-09 15:58 UTC, muwyse commented on bp_me/src/v/cache/bp_me_bedrock_register.sv
> +module bp_me_bedrock_register
A comment or two about this module could be helpful. I initially thought, based on the name, that this module would be holding the registered data internally. But, if I understand correctly, it is actually generating the read/write signals for some els_p set of registers, each reg_width_p wide. For read requests it generates r_v_o output and the next cycle the data is valid on data_i, which is then formed into the mem_resp_data_o, correct?

2021-06-09 15:58 UTC, muwyse commented on bp_me/src/v/cache/bp_me_bedrock_register.sv
> +   header_fifo
rename to cmd_fifo? Buffers header and a data word.

2021-06-10 00:28 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_bedrock_register.sv
> +   , input                                          mem_resp_ready_and_i
Yeah I'm fine with that. I figured users would just hardcode the signals outside of the module, but it's more clear to stub it inside

2021-06-10 00:29 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_bedrock_register.sv
> +   , input                                          mem_resp_ready_and_i
It actually does support multi-beat messages implicitly, since the autoincrement happens and last is ignored

2021-06-10 01:09 UTC, muwyse commented on bp_me/src/v/cache/bp_me_bedrock_register.sv
> +   , input                                          mem_resp_ready_and_i
> It actually does support multi-beat messages implicitly, since the autoincrement happens and last is ignored

lol, fair.

> Yeah I'm fine with that. I figured users would just hardcode the signals outside of the module, but it's more clear to stub it inside

Agreed. Stubbing the signals in this module makes it clearer.

2021-06-10 01:50 UTC, dpetrisko commented on bp_me/src/v/cache/bp_me_bedrock_register.sv
> +module bp_me_bedrock_register
added comments!

2021-06-10 01:52 UTC, dpetrisko commented
Comments addressed, thanks!

2021-06-10 01:57 UTC, muwyse approved these changes
LGTM!

2021-06-10 02:01 UTC, merged