Zynq opt
black-parrot/black-parrot pull request #899
Opened 2021-07-17 08:23 UTC by mysoreanoop

Thanks for contributing to BlackParrot! Check out the CONTRIBUTING guide, if this is your first
time. A few details to check:

## Issue Fixed
Does this PR address a BlackParrot GitHub issue? Link it here:

## Area
Module/tool/makefile/script in question.
bp_be_pipe_fma.v, Vivado, Zynq 7020

## Reasoning (outdated, confusing, verbose, etc.)
Why is this change required?
For devices/tools that do not do the necessary retiming automatically

## Additional Changes Required (if any)
Next steps, downstream modules affected, etc.
Once HardFloat changes are pulled, we can set manual latency distribution; otherwise unchanged.
[Ref](https://github.com/bsg-external/HardFloat/pull/8)

## Analysis
Potential impact of the change.
None as is

## Verification
Steps to taken to verify the change.
None, open to suggestions

## Additional Context
Add any other context about the problem here.
Logs, screenshots or videos that show the issue are very helpful.

2021-07-17 09:13 UTC, dpetrisko commented
Hi, thanks for the PR. You can embed these retiming registers at the input/output of the FMA unit and that should get the same QoR as having them in bp_be_pipe_fma, but will be a lot cleaner (as long as cross-boundary retiming / ungrouping is enabled for the FPU).

2021-07-17 09:14 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
> + *   FPGA retiming parameter array is used to distribute the latency manually
A diagram like this would be useful in the hardfloat module as well

2021-07-17 09:15 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
> +   , parameter integer latency_dstr_p[0:2] = {0,0,0} //Default = all retiming DFFs at the terminal DFF chain
What are these set to in the zynq?

2021-07-17 09:16 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
> +     ,.latencyDstr({latency_dstr_p[0], latency_dstr_p[1]})
{1, 0}?

2021-07-17 09:19 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
> +   , parameter integer latency_dstr_p[0:2] = {0,0,0} //Default = all retiming DFFs at the terminal DFF chain
Also, rather than having each independent, it's usually cleaner to do have it aggregate such as https://github.com/bespoke-silicon-group/basejump_stl/blob/master/bsg_noc/bsg_wormhole_router.v#L16 does it. Then you can use the latencies directly in most places, rather than needing to sum each

2021-07-17 09:21 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
> +  logic invalid_exc_n, is_nan_n, is_inf_n, is_zero_n;
These should get absorbed based on my high level comment, but in general:
basejump_stl convention is _r for registered values, and _n for next values. Even if they are latched in the module, from the perspective of these wires they are _r.

2021-07-17 09:21 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
>    bsg_dff_chain
Does bsg_dff_chain handle the zero case?

2021-07-17 09:22 UTC, dpetrisko requested changes
Thanks! changes requested, but mostly in hardfloat

2021-07-17 11:32 UTC, mysoreanoop commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
>    bsg_dff_chain
Yes, it becomes a wire assignment essentially; also, should we hook up the flush connection to a "reset-capable" bsg_dff_chain?

2021-07-17 12:16 UTC, mysoreanoop commented
> Hi, thanks for the PR. You can embed these retiming registers at the input/output of the FMA unit and that should get the same QoR as having them in bp_be_pipe_fma, but will be a lot cleaner (as long as cross-boundary retiming / ungrouping is enabled for the FPU).

I tried using the `-retiming` and `-flatten_hierarchy rebuilt/full` options, but couldn't replicate the results from when having this manually placed retiming DFF. Could I be using the tool wrongly maybe?

2021-07-17 21:08 UTC, taylor-bsg commented
Dan is saying that we can remove the retiming registers from the BP code, and just feed in a different set of retiming parameters for ASIC versus Zynq. 

Dan, seems like we would scoop the *= operator into a bsg_mul_add module which takes a pipeline parameter and then use /hard to vector to FPGA versus ASIC implementation? That seems like a reasonable way to abstract it in a more general way?

2021-07-18 07:00 UTC, mysoreanoop commented
> Dan is saying that we can remove the retiming registers from the BP code, and just feed in a different set of retiming parameters for ASIC versus Zynq.

I meant without manually distributing some of the trailing retiming_chain registers, I'm unable to get Vivado to automatically retime the bp_be_pipe_fma module just as well. Either way, it's a difference of ~3 ns, and none of the paths are even close to violating timing at 50 MHz, so I'll go ahead and remove them.

> Dan, seems like we would scoop the *= operator into a bsg_mul_add module which takes a pipeline parameter and then use /hard to vector to FPGA versus ASIC implementation? That seems like a reasonable way to abstract it in a more general way?

I have the suggested changes integrated with HardFloat, and I can get this done too if you decide to have it that way.

2021-07-18 07:56 UTC, dpetrisko commented
>Dan, seems like we would scoop the *= operator into a bsg_mul_add module which takes a pipeline parameter and then use /hard to vector to FPGA versus ASIC implementation? That seems like a reasonable way to abstract it in a more general way?

I think that's reasonable, but the latency distribution parameter is still needed to handle the swap, to know how many cycles to pause after the muladd

2021-07-18 07:58 UTC, dpetrisko commented
>Could I be using the tool wrongly maybe?

It seems like you're doing the right thing. Ungrouping / flattening should mean that having the flops on either side of the boundary is identical to the other. However, another student has also observed seemingly random limitations in Vivado, making me think the internal representations are not what you'd expect.

>Either way, it's a difference of ~3 ns, and none of the paths are even close to violating timing at 50 MHz, so I'll go ahead and remove them.

This could just be noise if there are other tighter paths

2021-07-18 07:59 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
>    bsg_dff_chain
cool! It's fine (and more efficient) without reset, because it's a datapath. So during a flush the control signals are zero'd and these are don't cared

2021-07-29 23:29 UTC, taylor-bsg commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
> +   , parameter int pipeline_stages_p[0:1] = {0,0},
@dpetrisko default should be 3,1 for ASIC and FPGA right? it can just be a local parameter?

2021-07-29 23:44 UTC, dpetrisko commented on bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
> +   , parameter int pipeline_stages_p[0:1] = {0,0},
Yeah I’m going to push through asic tools to verify that the rounding flop doesn’t impact qor and then we should just use the FMA and IMUL latency directly. I’m wary of parameterizations that break functionality for any but default value

2021-09-10 08:56 UTC, dpetrisko approved these changes
Great work!

2021-09-10 08:56 UTC, merged